import { Metadata } from 'next'
import { MainHeader } from '@/components/layout/main-header'
import { Footer } from '@/components/footer'
import { Card, CardContent } from '@/components/ui/card'

export const metadata: Metadata = {
  title: 'Terms of Service - BizoSaaS AI Marketing Platform',
  description: 'Terms and conditions for using BizoSaaS AI marketing automation platform and services.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <MainHeader />
      
      <div className="container mx-auto px-4 py-16">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
          <p className="text-muted-foreground mb-8">
            Last updated: January 1, 2025
          </p>

          <Card className="mb-8">
            <CardContent className="p-8 prose prose-gray max-w-none dark:prose-invert">
              <h2>1. Agreement to Terms</h2>
              <p>
                By accessing or using BizoSaaS ("Service"), you agree to be bound by these Terms of Service 
                ("Terms"). If you disagree with any part of these terms, you may not access the Service.
              </p>

              <h2>2. Description of Service</h2>
              <p>
                BizoSaaS is an AI-powered marketing automation platform that provides:
              </p>
              <ul>
                <li>Autonomous AI marketing agents</li>
                <li>Campaign optimization and management</li>
                <li>Multi-channel integration capabilities</li>
                <li>Analytics and reporting tools</li>
                <li>Lead generation and scoring</li>
              </ul>

              <h2>3. User Accounts</h2>
              
              <h3>Registration</h3>
              <p>
                To use our Service, you must create an account by providing accurate, complete, and current 
                information. You are responsible for maintaining the security of your account credentials.
              </p>

              <h3>Account Responsibilities</h3>
              <ul>
                <li>You must be at least 18 years old to use the Service</li>
                <li>Provide accurate and truthful information</li>
                <li>Maintain the security of your login credentials</li>
                <li>Notify us immediately of any unauthorized access</li>
                <li>Accept responsibility for all activities under your account</li>
              </ul>

              <h2>4. Acceptable Use Policy</h2>
              
              <h3>Permitted Uses</h3>
              <p>You may use the Service for legitimate marketing and business purposes in compliance with applicable laws.</p>

              <h3>Prohibited Uses</h3>
              <p>You agree not to use the Service to:</p>
              <ul>
                <li>Send spam or unsolicited communications</li>
                <li>Violate any applicable laws or regulations</li>
                <li>Infringe on intellectual property rights</li>
                <li>Distribute malware or harmful content</li>
                <li>Attempt to reverse engineer or hack the platform</li>
                <li>Use the Service for illegal or fraudulent activities</li>
                <li>Harass, abuse, or harm other users</li>
              </ul>

              <h2>5. Subscription and Billing</h2>
              
              <h3>Subscription Plans</h3>
              <p>
                We offer various subscription plans with different features and usage limits. Current pricing 
                is available on our pricing page.
              </p>

              <h3>Payment Terms</h3>
              <ul>
                <li>Subscriptions are billed in advance on a monthly or annual basis</li>
                <li>Payment is due immediately upon subscription activation</li>
                <li>All fees are non-refundable except as required by law</li>
                <li>We may change pricing with 30 days notice</li>
              </ul>

              <h3>Cancellation</h3>
              <p>
                You may cancel your subscription at any time. Cancellation will be effective at the end of 
                your current billing period.
              </p>

              <h2>6. Intellectual Property Rights</h2>
              
              <h3>Our Rights</h3>
              <p>
                The Service, including all software, algorithms, designs, and content, is owned by BizoSaaS 
                and protected by intellectual property laws.
              </p>

              <h3>Your Content</h3>
              <p>
                You retain ownership of content you upload to the Service. By using the Service, you grant 
                us a license to use your content to provide and improve the Service.
              </p>

              <h3>AI-Generated Content</h3>
              <p>
                Content generated by our AI agents based on your inputs belongs to you, subject to our 
                platform's terms and applicable laws.
              </p>

              <h2>7. Privacy and Data Protection</h2>
              <p>
                Your privacy is important to us. Our Privacy Policy explains how we collect, use, and protect 
                your information. By using the Service, you consent to our privacy practices.
              </p>

              <h2>8. Service Availability</h2>
              
              <h3>Uptime</h3>
              <p>
                We strive to maintain 99.9% uptime but cannot guarantee uninterrupted service. We may 
                temporarily suspend the Service for maintenance or updates.
              </p>

              <h3>Support</h3>
              <p>
                We provide customer support through email and our help center. Response times vary by 
                subscription plan.
              </p>

              <h2>9. Limitation of Liability</h2>
              <p>
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, BIZOSAAS SHALL NOT BE LIABLE FOR ANY INDIRECT, 
                INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES.
              </p>

              <h2>10. Warranties Disclaimer</h2>
              <p>
                THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DISCLAIM ALL WARRANTIES, 
                WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WARRANTIES OF MERCHANTABILITY AND FITNESS 
                FOR A PARTICULAR PURPOSE.
              </p>

              <h2>11. Indemnification</h2>
              <p>
                You agree to indemnify and hold BizoSaaS harmless from any claims, damages, or expenses 
                arising from your use of the Service or violation of these Terms.
              </p>

              <h2>12. Termination</h2>
              
              <h3>Termination by You</h3>
              <p>You may terminate your account at any time by canceling your subscription.</p>

              <h3>Termination by Us</h3>
              <p>
                We may suspend or terminate your account if you violate these Terms, fail to pay fees, 
                or engage in prohibited activities.
              </p>

              <h3>Effect of Termination</h3>
              <p>
                Upon termination, your access to the Service will cease, and we may delete your data 
                according to our retention policy.
              </p>

              <h2>13. Changes to Terms</h2>
              <p>
                We may update these Terms from time to time. We will notify you of material changes and 
                your continued use of the Service constitutes acceptance of the updated Terms.
              </p>

              <h2>14. Governing Law</h2>
              <p>
                These Terms are governed by the laws of the State of California, without regard to conflict 
                of law principles.
              </p>

              <h2>15. Dispute Resolution</h2>
              
              <h3>Arbitration</h3>
              <p>
                Any disputes arising under these Terms will be resolved through binding arbitration in 
                San Francisco, California, rather than in court.
              </p>

              <h3>Class Action Waiver</h3>
              <p>
                You agree not to participate in class action lawsuits against BizoSaaS related to the Service.
              </p>

              <h2>16. Severability</h2>
              <p>
                If any provision of these Terms is found to be unenforceable, the remaining provisions 
                will remain in full force and effect.
              </p>

              <h2>17. Contact Information</h2>
              <p>
                If you have questions about these Terms of Service, please contact us:
              </p>
              <ul>
                <li><strong>Email:</strong> legal@bizosaas.com</li>
                <li><strong>Address:</strong> BizoSaaS, Inc., 1234 Innovation Drive, San Francisco, CA 94105</li>
                <li><strong>Phone:</strong> +1 (555) 123-4567</li>
              </ul>

              <p>
                <strong>By using BizoSaaS, you acknowledge that you have read, understood, and agree to be 
                bound by these Terms of Service.</strong>
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
      
      <Footer />
    </div>
  )
}