# Temporal Development Configuration
# Basic configuration for development environment with PostgreSQL

# Worker configuration
worker.deactivateTaskQueueTimeoutMs: 5000
worker.pollerAutoScaleBaseline: 100

# History service configuration  
history.persistenceMaxQPS: 3000
history.historyMgrNumConns: 10

# Matching service configuration
matching.enableTasklistOwnership: true
matching.numWorkerBuildIdRefreshGoroutines: 10

# Frontend service configuration
frontend.persistenceGlobalMaxQPS: 2000
frontend.historyMaxPageSize: 5000

# System limits
system.enableGlobalNamespaceState: false
system.enableParentClosePolicy: true

# SQL configuration
sql.defaultDB: temporal
sql.maxConnLifetime: 3600s

# Namespace configuration
namespace.enableLocalArchival: false
namespace.enableGlobalNamespace: false

# Replication configuration (disabled for single-node setup)
replication.maxReplicationTaskSize: 262144

# Archival configuration (disabled for development)
archival.history.state: "disabled"
archival.visibility.state: "disabled"

# Visibility configuration
visibility.maxQPS: 2000
visibility.minRetentionDays: 1