# ========================================
# MESSAGE BROKERS - OFFICIAL DOCKER IMAGES
# ========================================
# Deploy this stack via Dokploy UI
# Project: infrastructure-services
#
# Services:
# 1. RabbitMQ - Task queue for AI agents
# 2. Apache Kafka - Event streaming platform
# 3. Kafka UI - Web UI for Kafka management
# ========================================

version: "3.8"

networks:
  dokploy-network:
    external: true

volumes:
  rabbitmq-data:
    driver: local
  kafka-data:
    driver: local
  kafka-logs:
    driver: local

services:
  # ==========================================
  # RABBITMQ - MESSAGE QUEUE
  # Official Image: rabbitmq:4.1-management
  # ==========================================
  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: bizosaas-rabbitmq
    hostname: rabbitmq

    networks:
      - dokploy-network

    ports:
      - "5672:5672"     # AMQP protocol
      - "15672:15672"   # Management UI
      - "15692:15692"   # Prometheus metrics

    environment:
      # Authentication
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: BizOSaaS2025@RabbitMQ

      # Management UI path prefix
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_management path_prefix "/rabbitmq"

      # Default virtual host
      RABBITMQ_DEFAULT_VHOST: /

      # Disk free limit
      RABBITMQ_DISK_FREE_LIMIT: 2GB

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

    restart: unless-stopped

    labels:
      # Dokploy labels
      - "com.dokploy.project=infrastructure-services"
      - "com.dokploy.service=rabbitmq"

      # Traefik routing - Management UI
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq-mgmt.rule=Host(`stg.bizoholic.com`) && PathPrefix(`/rabbitmq`)"
      - "traefik.http.routers.rabbitmq-mgmt.entrypoints=websecure"
      - "traefik.http.routers.rabbitmq-mgmt.tls.certresolver=letsencrypt"
      - "traefik.http.routers.rabbitmq-mgmt.priority=20"
      - "traefik.http.routers.rabbitmq-mgmt.service=rabbitmq-mgmt"
      - "traefik.http.services.rabbitmq-mgmt.loadbalancer.server.port=15672"

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  # ==========================================
  # APACHE KAFKA - EVENT STREAMING
  # Official Image: apache/kafka:4.0.1
  # KRaft mode (no Zookeeper needed)
  # ==========================================
  kafka:
    image: apache/kafka:4.0.1
    container_name: bizosaas-kafka
    hostname: kafka

    networks:
      - dokploy-network

    ports:
      - "9092:9092"     # Kafka broker (internal)
      - "9093:9093"     # Kafka broker (external)
      - "9094:9094"     # Kafka controller

    environment:
      # Cluster ID (generate with: kafka-storage random-uuid)
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

      # KRaft mode configuration (no Zookeeper)
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Listeners configuration
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9094,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://stg.bizoholic.com:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Log configuration
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000

      # Auto-create topics
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1

      # Performance tuning
      KAFKA_NUM_NETWORK_THREADS: 8
      KAFKA_NUM_IO_THREADS: 8
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 102400
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 102400
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600

      # JVM settings
      KAFKA_HEAP_OPTS: "-Xmx2G -Xms1G"

    volumes:
      - kafka-data:/var/lib/kafka/data
      - kafka-logs:/var/lib/kafka/logs

    restart: unless-stopped

    labels:
      # Dokploy labels
      - "com.dokploy.project=infrastructure-services"
      - "com.dokploy.service=kafka"

      # Traefik routing - Kafka broker (external access)
      - "traefik.enable=true"
      - "traefik.tcp.routers.kafka-external.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.kafka-external.entrypoints=kafka"
      - "traefik.tcp.routers.kafka-external.service=kafka-external"
      - "traefik.tcp.services.kafka-external.loadbalancer.server.port=9093"

    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 90s

    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

  # ==========================================
  # KAFKA UI - WEB MANAGEMENT INTERFACE
  # Official Image: provectuslabs/kafka-ui
  # ==========================================
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: bizosaas-kafka-ui
    hostname: kafka-ui

    networks:
      - dokploy-network

    ports:
      - "8080:8080"

    environment:
      # Kafka cluster connection
      KAFKA_CLUSTERS_0_NAME: bizosaas-production
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT

      # UI configuration
      DYNAMIC_CONFIG_ENABLED: "true"
      AUTH_TYPE: "DISABLED"

      # Server configuration
      SERVER_SERVLET_CONTEXT_PATH: /kafka-ui

    depends_on:
      - kafka

    restart: unless-stopped

    labels:
      # Dokploy labels
      - "com.dokploy.project=infrastructure-services"
      - "com.dokploy.service=kafka-ui"

      # Traefik routing - Web UI
      - "traefik.enable=true"
      - "traefik.http.routers.kafka-ui.rule=Host(`stg.bizoholic.com`) && PathPrefix(`/kafka-ui`)"
      - "traefik.http.routers.kafka-ui.entrypoints=websecure"
      - "traefik.http.routers.kafka-ui.tls.certresolver=letsencrypt"
      - "traefik.http.routers.kafka-ui.priority=20"
      - "traefik.http.routers.kafka-ui.service=kafka-ui"
      - "traefik.http.services.kafka-ui.loadbalancer.server.port=8080"

    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/kafka-ui/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
