version: "3.8"

services:
  plane-web:
    image: makeplane/plane-frontend:stable
    restart: unless-stopped
    volumes:
      - /var/www/plane/logs:/app/logs
    environment:
      - NEXT_PUBLIC_API_BASE_URL=https://plane-api.bizoholic.net
      - NEXT_PUBLIC_DEPLOY_URL=https://plane.bizoholic.net
      # Authentik SSO
      - AUTHENTIK_CLIENT_ID=08rwr1J2kGCnIgUPEdm9FHG2XOwPqL0NmCe3edi8
      - AUTHENTIK_CLIENT_SECRET=HphPzREPM5TlPcgOxf6k5iXJAnFtcThBFS1d8zPoFcV9zzTV3pRgKFBysM2rdNFCZg7ApDweACM06e6H428faOPj5RDNDuuhliCqyYNuBsATOmM7RmvdRjWn4GUJMsIL
    networks:
      - dokploy-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plane-web.rule=Host(`plane.bizoholic.net`)"
      - "traefik.http.routers.plane-web.entrypoints=websecure"
      - "traefik.http.routers.plane-web.tls.certresolver=myresolver"
      - "traefik.http.services.plane-web.loadbalancer.server.port=3000"

  plane-api:
    image: makeplane/plane-backend:stable
    restart: unless-stopped
    depends_on:
      - plane-worker
      - plane-beat
    volumes:
      - /var/www/plane/logs:/app/logs
      - plane_media:/app/media
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/plane_db
      - REDIS_URL=redis://bizosaas-redis-staging:6379/4
      - CELERY_BROKER_URL=redis://bizosaas-redis-staging:6379/4
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=1
      - WEB_URL=https://plane.bizoholic.net
      - CORS_ALLOWED_ORIGINS=https://plane.bizoholic.net
      - SECRET_KEY=${PLANE_SECRET_KEY}
      - GUNICORN_WORKERS=1
      - GUNICORN_TIMEOUT=300
      - GUNICORN_MAX_REQUESTS=500
      - GUNICORN_MAX_REQUESTS_JITTER=100
    networks:
      - dokploy-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plane-api.rule=Host(`plane-api.bizoholic.net`)"
      - "traefik.http.routers.plane-api.entrypoints=websecure"
      - "traefik.http.routers.plane-api.tls.certresolver=myresolver"
      - "traefik.http.services.plane-api.loadbalancer.server.port=8000"

  plane-worker:
    image: makeplane/plane-backend:stable
    restart: unless-stopped
    command: ./bin/docker-entrypoint-worker.sh
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/plane_db
      - REDIS_URL=redis://bizosaas-redis-staging:6379/4
      - CELERY_BROKER_URL=redis://bizosaas-redis-staging:6379/4
      - SECRET_KEY=${PLANE_SECRET_KEY}
    networks:
      - dokploy-network
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 384M
        reservations:
          cpus: '0.1'
          memory: 128M

  plane-beat:
    image: makeplane/plane-backend:stable
    restart: unless-stopped
    command: ./bin/docker-entrypoint-beat.sh
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/plane_db
      - REDIS_URL=redis://bizosaas-redis-staging:6379/4
      - SECRET_KEY=${PLANE_SECRET_KEY}
    networks:
      - dokploy-network
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.05'
          memory: 64M

volumes:
  plane_media:

networks:
  dokploy-network:
    external: true
