version: '3.8'

# Lago Billing - Optimized Staging Deployment
# Connects to shared Infrastructure (Postgres/Redis) to save resources.

services:
  # ============================
  # LAGO API
  # ============================
  lago-api:
    image: getlago/api:v1.16.0
    container_name: lago-api
    restart: unless-stopped
    depends_on:
      - lago-worker
    environment:
      - DATABASE_URL=postgresql://admin:QWyfkmjcfbpYnMDkxqzAOJBcPvlZCtkh8R%2F%2BDTz%2BSkA%3D@bizosaas-postgres-staging:5432/lago
      - REDIS_URL=redis://bizosaas-redis-staging:6379/5
      - LAGO_REDIS_CACHE_URL=redis://bizosaas-redis-staging:6379/5
      - LAGO_SIDEKIQ_REDIS_URL=redis://bizosaas-redis-staging:6379/5
      - LAGO_API_URL=http://lago-api:3000
      - LAGO_FRONT_URL=http://lago-front:80
      - LAGO_DISABLE_SEGMENT=true
      # Values to be set in Dokploy UI
      - LAGO_SECRET_KEY_BASE=${LAGO_SECRET_KEY_BASE}
      - LAGO_RSA_PRIVATE_KEY=${LAGO_RSA_PRIVATE_KEY}
      - LAGO_ENCRYPTION_PRIMARY_KEY=${LAGO_ENCRYPTION_PRIMARY_KEY}
      - LAGO_ENCRYPTION_DETERMINISTIC_KEY=${LAGO_ENCRYPTION_DETERMINISTIC_KEY}
      - LAGO_ENCRYPTION_KEY_DERIVATION_SALT=${LAGO_ENCRYPTION_KEY_DERIVATION_SALT}
      - RAILS_ENV=production
      - LAGO_DISABLE_SIGNUP=false
    networks:
      - dokploy-network
    ports:
      - "3000"

  # ============================
  # LAGO WORKER
  # ============================
  lago-worker:
    image: getlago/api:v1.16.0
    container_name: lago-worker
    restart: unless-stopped
    command: ./scripts/start.worker.sh
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/lago
      - REDIS_URL=redis://bizosaas-redis-staging:6379/5
      - LAGO_REDIS_CACHE_URL=redis://bizosaas-redis-staging:6379/5
      - LAGO_SIDEKIQ_REDIS_URL=redis://bizosaas-redis-staging:6379/5
      - LAGO_API_URL=http://lago-api:3000
      - LAGO_FRONT_URL=http://lago-front:80
      - LAGO_DISABLE_SEGMENT=true
      # Values to be set in Dokploy UI
      - LAGO_SECRET_KEY_BASE=${LAGO_SECRET_KEY_BASE}
      - LAGO_RSA_PRIVATE_KEY=${LAGO_RSA_PRIVATE_KEY}
      - LAGO_ENCRYPTION_PRIMARY_KEY=${LAGO_ENCRYPTION_PRIMARY_KEY}
      - LAGO_ENCRYPTION_DETERMINISTIC_KEY=${LAGO_ENCRYPTION_DETERMINISTIC_KEY}
      - LAGO_ENCRYPTION_KEY_DERIVATION_SALT=${LAGO_ENCRYPTION_KEY_DERIVATION_SALT}
      - RAILS_ENV=production
    networks:
      - dokploy-network

  # ============================
  # LAGO FRONTEND
  # ============================
  lago-front:
    image: getlago/front:v1.16.0
    container_name: lago-front
    restart: unless-stopped
    depends_on:
      - lago-api
    environment:
      - API_URL=http://lago-api:3000
      - API_BASE_URL=/
    networks:
      - dokploy-network
    ports:
      - "8088:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lago-front.rule=Host(`billing.bizoholic.net`)"
      - "traefik.http.routers.lago-front.entrypoints=websecure"
      - "traefik.http.routers.lago-front.tls.certresolver=myresolver"
      - "traefik.http.services.lago-front.loadbalancer.server.port=80"

  # ============================
  # MIGRATION UTILITY
  # ============================
  lago-migrate:
    image: getlago/api:v1.16.0
    command: [ "./scripts/migrate.sh" ]
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${LAGO_POSTGRES_DB:-lago}
      - REDIS_URL=redis://redis:6379/5
      - SECRET_KEY_BASE=${LAGO_SECRET_KEY_BASE}
      - LAGO_RSA_PRIVATE_KEY=${LAGO_RSA_PRIVATE_KEY}
      - LAGO_ENCRYPTION_PRIMARY_KEY=${LAGO_ENCRYPTION_PRIMARY_KEY}
      - LAGO_ENCRYPTION_DETERMINISTIC_KEY=${LAGO_ENCRYPTION_DETERMINISTIC_KEY}
      - LAGO_ENCRYPTION_KEY_DERIVATION_SALT=${LAGO_ENCRYPTION_KEY_DERIVATION_SALT}
      - RAILS_ENV=production
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
