version: "3.9"
services:
  # ==========================================
  # 1. BRAIN API GATEWAY (Port 8001) - CORE
  # ==========================================
  # FIX: Switch to build on server to ensure latest code from staging branch
  brain-api:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/brain-gateway:staging
    pull_policy: always
    container_name: bizosaas-brain-staging
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/bizosaas_staging
      - REDIS_URL=redis://bizosaas-redis-staging:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ENVIRONMENT=staging
      - LOG_LEVEL=INFO
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`api.bizoholic.net`)"
      - "traefik.http.routers.gateway.entrypoints=websecure"
      - "traefik.http.routers.gateway.tls.certresolver=letsencrypt"
      - "traefik.http.services.gateway.loadbalancer.server.port=8000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M

  # ==========================================
  # 2. AUTHENTICATION SERVICE (Port 8006)
  # ==========================================
  auth-service:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/auth-service:staging
    pull_policy: always
    container_name: bizosaas-auth-service-staging
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8006", "--workers", "1"]
    ports:
      - "8006:8006"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.bizoholic.net`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls.certresolver=letsencrypt"
      - "traefik.http.services.auth.loadbalancer.server.port=8006"
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/bizosaas_staging
      - DATABASE_URL_FIX=postgresql+asyncpg://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/bizosaas_staging
      - REDIS_URL=redis://bizosaas-redis-staging:6379/10
      - SECRET_KEY=staging-secret-key-auth-bizosaas-2025-v1
      - JWT_SECRET=staging-jwt-secret-bizosaas-2025-secure
      - ENVIRONMENT=staging
      - PORT=8006
      - ALLOWED_ORIGINS=*
      - LOG_LEVEL=INFO
    networks:
      - dokploy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.05'
          memory: 128M
    healthcheck:
      test: ["CMD-SHELL", "python3 -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8006/health\")' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  # ==========================================
  # 3. AI AGENTS (Port 8008)
  # ==========================================
  ai-agents:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/ai-agents:staging
    pull_policy: always
    container_name: bizosaas-ai-agents-staging
    ports:
      - "8008:8002"
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/bizosaas_staging
      - REDIS_URL=redis://bizosaas-redis-staging:6379/8
      - BRAIN_API_URL=http://bizosaas-brain-staging:8001
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ENVIRONMENT=staging
    networks:
      - dokploy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8002/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # NOTE: The following services (Wagtail, DjangoCRM, Saleor) are disabled 
  # as the platform uses external connectors.
  
  # business-directory-backend: ...
  # coreldove-backend: ...
  # amazon-sourcing: ...

networks:
  dokploy-network:
    external: true
