# BizOSaaS Backend Services - STAGING (Using Local Pre-Built Images)
# Working local images transferred directly to VPS
# Deploy via Dokploy at dk.bizoholic.com

services:
  # ==========================================
  # 1. SALEOR E-COMMERCE API (Port 8000)
  # ==========================================
  saleor-api:
    image: ghcr.io/saleor/saleor:3.20
    container_name: bizosaas-saleor-staging
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://admin:BizOSaaS2025!StagingDB@194.238.16.237:5433/saleor_staging
      - REDIS_URL=redis://194.238.16.237:6380/1
      - SECRET_KEY=staging-secret-key-saleor-bizosaas-2025
      - ALLOWED_HOSTS=194.238.16.237,localhost,stg.coreldove.com
      - ALLOWED_CLIENT_HOSTS=194.238.16.237,localhost,stg.coreldove.com
      - DEBUG=True
      - ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL=False
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==========================================
  # 2. BRAIN API - AI Gateway (Port 8001)
  # ==========================================
  brain-api:
    image: bizosaas-brain-gateway:latest
    container_name: bizosaas-brain-staging
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@194.238.16.237:5433/bizosaas_staging
      - REDIS_URL=redis://194.238.16.237:6380/0
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ENVIRONMENT=staging
      - LOG_LEVEL=INFO
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==========================================
  # 2. WAGTAIL CMS (Port 8002)
  # ==========================================
  wagtail-cms:
    image: bizosaas-wagtail-cms:latest
    container_name: bizosaas-wagtail-staging
    ports:
      - "8002:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=wagtail_cms.settings.production
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@194.238.16.237:5433/bizosaas_staging
      - REDIS_URL=redis://194.238.16.237:6380/3
      - SECRET_KEY=staging-secret-key-wagtail-bizosaas-2025
      - ALLOWED_HOSTS=194.238.16.237,localhost,stg.bizoholic.com
      - DEBUG=False
      - VAULT_ADDR=http://bizosaas-vault-staging:8200
      - VAULT_TOKEN=bizosaas-dev-root-token
      - VAULT_MOUNT_PATH=bizosaas
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # 3. DJANGO CRM (Port 8003)
  # ==========================================
  django-crm:
    image: bizoholic-django-crm:latest
    container_name: bizosaas-django-crm-staging
    ports:
      - "8003:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=crm_project.settings.production
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@194.238.16.237:5433/bizosaas_staging
      - REDIS_URL=redis://194.238.16.237:6380/4
      - SECRET_KEY=staging-secret-key-djangocrm-bizosaas-2025
      - ALLOWED_HOSTS=194.238.16.237,localhost,stg.bizoholic.com
      - DEBUG=False
      - VAULT_ADDR=http://bizosaas-vault-staging:8200
      - VAULT_TOKEN=bizosaas-dev-root-token
      - VAULT_MOUNT_PATH=bizosaas
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # 4. BUSINESS DIRECTORY BACKEND (Port 8004)
  # ==========================================
  business-directory-backend:
    image: bizosaas-business-directory-backend:latest
    container_name: bizosaas-business-directory-staging
    ports:
      - "8004:8000"
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@194.238.16.237:5433/bizosaas_staging
      - REDIS_URL=redis://194.238.16.237:6380/5
      - SECRET_KEY=staging-secret-key-bizdir-bizosaas-2025
      - ENVIRONMENT=staging
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # 5. CORELDOVE BACKEND (Port 8005)
  # ==========================================
  coreldove-backend:
    image: bizoholic-coreldove-backend:latest
    container_name: bizosaas-coreldove-backend-staging
    ports:
      - "8005:8000"
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@194.238.16.237:5433/bizosaas_staging
      - REDIS_URL=redis://194.238.16.237:6380/6
      - SECRET_KEY=staging-secret-key-coreldove-bizosaas-2025
      - ENVIRONMENT=staging
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # 6. AI AGENTS (Port 8008)
  # ==========================================
  ai-agents:
    image: bizoholic-ai-agents:latest
    container_name: bizosaas-ai-agents-staging
    ports:
      - "8008:8000"
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@194.238.16.237:5433/bizosaas_staging
      - REDIS_URL=redis://194.238.16.237:6380/8
      - BRAIN_API_URL=http://bizosaas-brain-staging:8001
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ENVIRONMENT=staging
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # 7. AMAZON SOURCING (Port 8009)
  # ==========================================
  amazon-sourcing:
    image: bizosaas/amazon-sourcing:latest
    container_name: bizosaas-amazon-sourcing-staging
    ports:
      - "8009:8000"
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@194.238.16.237:5433/bizosaas_staging
      - REDIS_URL=redis://194.238.16.237:6380/9
      - AMAZON_ACCESS_KEY=${AMAZON_ACCESS_KEY:-}
      - AMAZON_SECRET_KEY=${AMAZON_SECRET_KEY:-}
      - ENVIRONMENT=staging
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # 8. AUTH SERVICE (Port 8006) - EXPERIMENTAL
  # ==========================================
  # Using backend-services-azbmbl-auth-service:latest (Dokploy built)
  auth-service:
    image: backend-services-azbmbl-auth-service:latest
    container_name: bizosaas-auth-service-staging
    ports:
      - "8006:8007"
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@194.238.16.237:5433/bizosaas_staging
      - REDIS_URL=redis://194.238.16.237:6380/10
      - SECRET_KEY=staging-secret-key-auth-bizosaas-2025-v1
      - JWT_SECRET=staging-jwt-secret-bizosaas-2025-secure
      - ENVIRONMENT=staging
      - PORT=8007
      - ALLOWED_ORIGINS=*
      - LOG_LEVEL=INFO
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==========================================
  # 9. QUANTTRADE BACKEND (Port 8012)
  # ==========================================
  quanttrade-backend:
    image: bizosaas/quanttrade-backend:staging
    container_name: bizosaas-quanttrade-backend-staging
    ports:
      - "8012:8000"
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@194.238.16.237:5433/bizosaas_staging
      - REDIS_URL=redis://194.238.16.237:6380/12
      - SECRET_KEY=staging-secret-key-quanttrade-bizosaas-2025
      - ENVIRONMENT=staging
      - BRAIN_API_URL=http://bizosaas-brain-staging:8001
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    external: true

# ==================================================
# DEPLOYMENT STRATEGY: Local Pre-Built Images
# ==================================================
# These images are already built and tested locally
# They have been transferred to VPS via docker save/load
# No GitHub build required - images ready to deploy
# ==================================================
