# BizOSaaS Frontend Services - STAGING Environment (Complete - All 6 Services)
# All public-facing frontend applications

services:
  # ==========================================
  # 1. BIZOHOLIC MARKETING WEBSITE
  # Domain: stg.bizoholic.com
  # ==========================================
  bizoholic-frontend:
    image: ghcr.io/bizoholic-digital/bizoholic-frontend:staging
    container_name: bizoholic-frontend-staging
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=staging
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_PUBLIC_SITE_URL=https://stg.bizoholic.com
      - ENVIRONMENT=staging
      - DEBUG_MODE=true
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bizoholic-staging.rule=Host(`stg.bizoholic.com`)"
      - "traefik.http.routers.bizoholic-staging.tls=true"
      - "traefik.http.routers.bizoholic-staging.tls.certresolver=letsencrypt"
      - "traefik.http.services.bizoholic-staging.loadbalancer.server.port=3000"

  # ==========================================
  # 2. CLIENT PORTAL
  # Domain: stg.portal.bizoholic.com
  # ==========================================
  client-portal:
    image: ghcr.io/bizoholic-digital/client-portal:staging
    container_name: client-portal-staging
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=staging
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_PUBLIC_SITE_URL=https://stg.portal.bizoholic.com
      - ENVIRONMENT=staging
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portal-staging.rule=Host(`stg.portal.bizoholic.com`)"
      - "traefik.http.routers.portal-staging.tls=true"
      - "traefik.http.routers.portal-staging.tls.certresolver=letsencrypt"
      - "traefik.http.services.portal-staging.loadbalancer.server.port=3000"

  # ==========================================
  # 3. CORELDOVE E-COMMERCE WEBSITE
  # Domain: stg.coreldove.com
  # ==========================================
  coreldove-frontend:
    image: ghcr.io/bizoholic-digital/coreldove-frontend:staging
    container_name: coreldove-frontend-staging
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=staging
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-saleor-staging:8000
      - NEXT_PUBLIC_SITE_URL=https://stg.coreldove.com
      - NEXT_PUBLIC_SALEOR_API_URL=http://bizosaas-saleor-staging:8000/graphql/
      - ENVIRONMENT=staging
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coreldove-staging.rule=Host(`stg.coreldove.com`)"
      - "traefik.http.routers.coreldove-staging.tls=true"
      - "traefik.http.routers.coreldove-staging.tls.certresolver=letsencrypt"
      - "traefik.http.services.coreldove-staging.loadbalancer.server.port=3002"

  # ==========================================
  # 4. BUSINESS DIRECTORY FRONTEND
  # Domain: stg.directory.bizoholic.com
  # ==========================================
  business-directory:
    image: ghcr.io/bizoholic-digital/business-directory-frontend:staging
    container_name: business-directory-staging
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=staging
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-directory-backend-staging:8004
      - NEXT_PUBLIC_SITE_URL=https://stg.directory.bizoholic.com
      - ENVIRONMENT=staging
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.directory-staging.rule=Host(`stg.directory.bizoholic.com`)"
      - "traefik.http.routers.directory-staging.tls=true"
      - "traefik.http.routers.directory-staging.tls.certresolver=letsencrypt"
      - "traefik.http.services.directory-staging.loadbalancer.server.port=3004"

  # ==========================================
  # 5. THRILLRING GAMING WEBSITE
  # Domain: stg.thrillring.com
  # ==========================================
  thrillring-gaming:
    image: node:20-alpine
    container_name: thrillring-gaming-staging
    ports:
      - "3005:3005"
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=staging
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_PUBLIC_SITE_URL=https://stg.thrillring.com
      - PORT=3005
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thrillring-staging.rule=Host(`stg.thrillring.com`)"
      - "traefik.http.routers.thrillring-staging.tls=true"
      - "traefik.http.routers.thrillring-staging.tls.certresolver=letsencrypt"
      - "traefik.http.services.thrillring-staging.loadbalancer.server.port=3005"

  # ==========================================
  # 6. ADMIN DASHBOARD
  # Domain: stg.admin.bizoholic.com
  # ==========================================
  admin-dashboard:
    image: ghcr.io/bizoholic-digital/admin-dashboard:staging
    container_name: admin-dashboard-staging
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=staging
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_PUBLIC_SITE_URL=https://stg.admin.bizoholic.com
      - ENVIRONMENT=staging
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin-staging.rule=Host(`stg.admin.bizoholic.com`)"
      - "traefik.http.routers.admin-staging.tls=true"
      - "traefik.http.routers.admin-staging.tls.certresolver=letsencrypt"
      - "traefik.http.services.admin-staging.loadbalancer.server.port=3009"

networks:
  dokploy-network:
    external: true

# ==================================================
# FRONTEND SERVICES PROJECT SUMMARY (COMPLETE):
# ==================================================
# Container Count: 6 (all frontend applications)
# Purpose: Public-facing websites for staging
# External Access: Via Traefik reverse proxy with SSL
# Domains:
#   1. stg.bizoholic.com - Marketing site
#   2. stg.portal.bizoholic.com - Client portal
#   3. stg.coreldove.com - E-commerce storefront
#   4. stg.directory.bizoholic.com - Business directory
#   5. stg.thrillring.com - Gaming website
#   6. stg.admin.bizoholic.com - Admin dashboard
# Dependencies: Backend APIs (Brain, Saleor, Directory)
# Note: All services except ThrillRing require images pushed to ghcr.io first
# ThrillRing: Needs app code volume-mounted or built image
# ==================================================
