services:
  authentik-server:
    image: ghcr.io/goauthentik/server:2025.10.3
    container_name: bizosaas-authentik-server
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: bizosaas-redis-staging
      AUTHENTIK_REDIS__PORT: "6379"
      AUTHENTIK_REDIS__DB: "1"
      AUTHENTIK_POSTGRESQL__HOST: bizosaas-postgres-staging
      AUTHENTIK_POSTGRESQL__PORT: "5432"
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: admin
      AUTHENTIK_POSTGRESQL__PASSWORD: BizOSaaS2025!StagingDB
      AUTHENTIK_BOOTSTRAP_PASSWORD: "BizOSaaS2025!AuthentikAdmin"
      AUTHENTIK_BOOTSTRAP_EMAIL: "admin@bizoholic.net"
      # Set in Dokploy UI
      AUTHENTIK_SECRET_KEY: "PN2d2fhSGsRJec9Wfwom4Rzmrv8wIk2H1KpL/pEaei8="
    volumes:
      - authentik_media:/media
      - authentik_templates:/templates
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentik.rule=Host(`sso.bizoholic.net`)"
      - "traefik.http.routers.authentik.entrypoints=websecure"
      - "traefik.http.routers.authentik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.authentik.priority=100"
      - "traefik.http.services.authentik.loadbalancer.server.port=9000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "python3 -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:9000/-/health/live/\")' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  authentik-worker:
    image: ghcr.io/goauthentik/server:2025.10.3
    container_name: bizosaas-authentik-worker
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: bizosaas-redis-staging
      AUTHENTIK_REDIS__PORT: "6379"
      AUTHENTIK_REDIS__DB: "1"
      AUTHENTIK_POSTGRESQL__HOST: bizosaas-postgres-staging
      AUTHENTIK_POSTGRESQL__PORT: "5432"
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: admin
      AUTHENTIK_POSTGRESQL__PASSWORD: BizOSaaS2025!StagingDB
      # Set in Dokploy UI
      AUTHENTIK_SECRET_KEY: "PN2d2fhSGsRJec9Wfwom4Rzmrv8wIk2H1KpL/pEaei8="
    volumes:
      - authentik_media:/media
      - authentik_templates:/templates
    networks:
      - dokploy-network
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 384M
        reservations:
          cpus: '0.1'
          memory: 128M
    healthcheck:
      test: ["CMD-SHELL", "celery -A authentik.root.celery inspect ping -d celery@$HOSTNAME"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  authentik_media:
  authentik_templates:

networks:
  dokploy-network:
    external: true
