# BizOSaaS Infrastructure Project - STAGING Environment
# 3 Core Infrastructure containers for staging deployment

services:
  # ==========================================
  # POSTGRESQL DATABASE
  # Multi-tenant database with pgvector
  # ==========================================
  postgres:
    image: pgvector/pgvector:pg16
    container_name: bizosaas-postgres-staging
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=bizosaas_staging
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=BizOSaaS2025!StagingDB
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d bizosaas_staging"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==========================================
  # REDIS CACHE
  # High-performance caching and sessions
  # ==========================================
  redis:
    image: redis:7-alpine
    container_name: bizosaas-redis-staging
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes --replica-read-only no
    volumes:
      - redis_staging_data:/data
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==========================================
  # HASHICORP VAULT
  # Secrets management
  # ==========================================
  vault:
    image: hashicorp/vault:1.15
    container_name: bizosaas-vault-staging
    ports:
      - "8201:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=staging-root-token-bizosaas-2025
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_staging_data:/vault/data
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==========================================
  # TEMPORAL SERVER
  # Workflow orchestration engine
  # ==========================================
  temporal-server:
    image: temporalio/auto-setup:1.22.0
    container_name: bizosaas-temporal-server-staging
    ports:
      - "7234:7233"
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PWD=QWyfkmjcfbpYnMDkxqzAOJBcPvlZCtkh8R/+DTz+SkA=
      - POSTGRES_SEEDS=bizosaas-postgres-staging
      - POSTGRES_DB=temporal
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    networks:
      - dokploy-network
    restart: unless-stopped
    depends_on:
      - postgres

  # ==========================================
  # TEMPORAL UI
  # Workflow management interface
  # ==========================================
  temporal-ui:
    image: temporalio/ui:2.21.0
    container_name: bizosaas-temporal-ui-staging
    ports:
      - "8083:8080"
    environment:
      - TEMPORAL_ADDRESS=bizosaas-temporal-server-staging:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8083
    networks:
      - dokploy-network
    restart: unless-stopped
    depends_on:
      - temporal-server

  # ==========================================
  # APACHE SUPERSET - DEPRECATED / REMOVED
  # Analytics and Business Intelligence
  # ==========================================
  # Service removed to save resources.
  # Use Grafana with Postgres datasource for BI.
  # MONITORING STACK
  # Prometheus, Grafana, Loki
  # ==========================================
  loki:
    image: grafana/loki:2.9.0
    container_name: bizosaas-loki-staging
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - dokploy-network
    restart: unless-stopped
    volumes:
      - loki_staging_data:/loki

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: bizosaas-prometheus-staging
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_staging_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - dokploy-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.0
    container_name: bizosaas-grafana-staging
    ports:
      - "8084:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=BizOSaaS2025!Grafana
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_staging_data:/var/lib/grafana
    networks:
      - dokploy-network
    restart: unless-stopped
    depends_on:
      - prometheus
      - loki
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  superset_home:
    driver: local
  postgres_staging_data:
    driver: local
  redis_staging_data:
    driver: local
  vault_staging_data:
    driver: local
  loki_staging_data:
    driver: local
  prometheus_staging_data:
    driver: local
  grafana_staging_data:
    driver: local

networks:
  dokploy-network:
    external: true

# ==================================================
# INFRASTRUCTURE PROJECT SUMMARY:
# ==================================================
# Container Count: 6 (complete infrastructure + analytics)
# Purpose: Complete infrastructure for staging environment
# External Access: PostgreSQL (5433), Redis (6380), Vault (8201), Temporal (7234), Temporal UI (8083), Superset (8088)
# Dependencies: None (foundation layer)
# Services:
#   - PostgreSQL with pgvector
#   - Redis cache
#   - Vault secrets management
#   - Temporal Server (workflow orchestration)
#   - Temporal UI (workflow management interface)
#   - Apache Superset (analytics and BI dashboards)
# ==================================================
