version: "3.8"
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID:-hvs.REpC92zP7vH29X04y1vX4Wn}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://127.0.0.1:8200
    command: server -dev -dev-root-token-id=${VAULT_DEV_ROOT_TOKEN_ID:-hvs.REpC92zP7vH29X04y1vX4Wn} -dev-listen-address=0.0.0.0:8200
    ports:
      - "8200:8200"
    volumes:
      - vault-data:/vault/file
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.vault-staging.rule=Host(`vault.bizoholic.net`)
      - traefik.http.routers.vault-staging.entrypoints=websecure
      - traefik.http.routers.vault-staging.tls.certresolver=letsencrypt
      - traefik.http.services.vault-staging.loadbalancer.server.port=8200
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
    name: dokploy-network

volumes:
  vault-data:
    name: vault-data-staging
