# BizOSaaS Infrastructure Project - STAGING Environment
# 3 Core Infrastructure containers for staging deployment

services:
  # ==========================================
  # POSTGRESQL DATABASE
  # Multi-tenant database with pgvector
  # ==========================================
  postgres:
    image: pgvector/pgvector:pg16
    container_name: bizosaas-postgres-staging
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=bizosaas_staging
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=BizOSaaS2025!StagingDB
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d bizosaas_staging"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==========================================
  # REDIS CACHE
  # High-performance caching and sessions
  # ==========================================
  redis:
    image: redis:7-alpine
    container_name: bizosaas-redis-staging
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes --replica-read-only no
    volumes:
      - redis_staging_data:/data
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==========================================
  # HASHICORP VAULT
  # Secrets management
  # ==========================================
  vault:
    image: hashicorp/vault:1.15
    container_name: bizosaas-vault-staging
    ports:
      - "8201:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=staging-root-token-bizosaas-2025
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_staging_data:/vault/data
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_staging_data:
    driver: local
  redis_staging_data:
    driver: local
  vault_staging_data:
    driver: local

networks:
  dokploy-network:
    external: true

# ==================================================
# INFRASTRUCTURE PROJECT SUMMARY:
# ==================================================
# Container Count: 3 (core infrastructure only)
# Purpose: Core infrastructure for staging environment
# External Access: PostgreSQL (5433), Redis (6380), Vault (8201)
# Dependencies: None (foundation layer)
# Note: Temporal services removed temporarily due to health check issues
# ==================================================
