# BizOSaaS Backend Services - STAGING Environment (Minimal - Pre-built Only)
# Using only pre-built images that work reliably

services:
  # ==========================================
  # SALEOR E-COMMERCE PLATFORM
  # Full-featured e-commerce API
  # ==========================================
  saleor-api:
    image: ghcr.io/saleor/saleor:3.20
    container_name: bizosaas-saleor-staging
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/saleor_staging
      - REDIS_URL=redis://bizosaas-redis-staging:6379/0
      - SECRET_KEY=staging-saleor-secret-key-bizosaas-2025
      - ALLOWED_HOSTS=stg.coreldove.com,bizosaas-saleor-staging,localhost
      - DEBUG=False
      - DEFAULT_FROM_EMAIL=noreply@stg.coreldove.com
      - CELERY_BROKER_URL=redis://bizosaas-redis-staging:6379/0
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health/')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  dokploy-network:
    external: true

# ==================================================
# BACKEND SERVICES PROJECT SUMMARY (MINIMAL):
# ==================================================
# Container Count: 1 (Saleor only - verified working)
# Purpose: E-commerce backend for staging
# Services:
#   - Saleor API (8000) - E-commerce platform ✅ PRE-BUILT IMAGE
# Note: This is a minimal config to get Saleor working
#       Custom services (Django CRM, Wagtail, Brain API) need
#       proper Dockerfile fixes before deployment
# Dependencies: Infrastructure (PostgreSQL, Redis)
# ==================================================
