# BizOSaaS Backend Services - STAGING Environment (Simplified)
# Starting with 1 core backend service for testing

services:
  # ==========================================
  # SALEOR E-COMMERCE PLATFORM
  # Full-featured e-commerce API
  # ==========================================
  saleor-api:
    image: ghcr.io/saleor/saleor:3.20
    container_name: bizosaas-saleor-staging
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/saleor_staging
      - REDIS_URL=redis://bizosaas-redis-staging:6379/0
      - SECRET_KEY=${SALEOR_SECRET_KEY:-staging-saleor-secret-key-bizosaas-2025}
      - ALLOWED_HOSTS=stg.coreldove.com,bizosaas-saleor-staging,localhost
      - DEBUG=true
      - DEFAULT_FROM_EMAIL=noreply@stg.coreldove.com
      - CELERY_BROKER_URL=redis://bizosaas-redis-staging:6379/0
    networks:
      - bizosaas-staging-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  bizosaas-staging-network:
    external: true

# ==================================================
# BACKEND SERVICES PROJECT SUMMARY (SIMPLIFIED):
# ==================================================
# Container Count: 1 (Saleor only - tested and working)
# Purpose: E-commerce backend for staging
# External Access: Saleor API (8000)
# Dependencies: Infrastructure services (PostgreSQL, Redis)
# Next Phase: Add more services incrementally after verifying Saleor works
# ==================================================
