version: '3.8'

# BizOSaaS Frontend Applications - Corrected Domain Strategy
# Deploy to Dokploy with proper domain routing

services:
  # ==========================================
  # BIZOHOLIC MARKETING WEBSITE
  # Domain: bizoholic.com
  # ==========================================
  bizoholic-frontend:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git
      dockerfile: frontend/apps/bizoholic-frontend/Dockerfile
    container_name: bizoholic-frontend-3000
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-unified:8001
      - NEXT_PUBLIC_SITE_URL=https://bizoholic.com
    networks:
      - bizosaas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bizoholic-main.rule=Host(`bizoholic.com`) && !PathPrefix(`/login`) && !PathPrefix(`/admin`)"
      - "traefik.http.routers.bizoholic-main.tls=true"
      - "traefik.http.routers.bizoholic-main.tls.certresolver=letsencrypt"
      - "traefik.http.routers.bizoholic-main.priority=1"

  # ==========================================
  # CORELDOVE E-COMMERCE WEBSITE
  # Domain: coreldove.com
  # ==========================================
  coreldove-frontend:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git
      dockerfile: frontend/apps/coreldove-frontend/Dockerfile
    container_name: coreldove-frontend-3002
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-unified:8001
      - NEXT_PUBLIC_SITE_URL=https://coreldove.com
      - NEXT_PUBLIC_SALEOR_API_URL=http://bizosaas-brain-unified:8001/api/brain/saleor
    networks:
      - bizosaas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coreldove.rule=Host(`coreldove.com`)"
      - "traefik.http.routers.coreldove.tls=true"
      - "traefik.http.routers.coreldove.tls.certresolver=letsencrypt"

  # ==========================================
  # THRILLRING GAMING WEBSITE
  # Domain: thrillring.com
  # ==========================================
  thrillring-gaming:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git
      dockerfile: frontend/apps/thrillring-gaming/Dockerfile
    container_name: thrillring-gaming-3005
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-unified:8001
      - NEXT_PUBLIC_SITE_URL=https://thrillring.com
    networks:
      - bizosaas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thrillring.rule=Host(`thrillring.com`)"
      - "traefik.http.routers.thrillring.tls=true"
      - "traefik.http.routers.thrillring.tls.certresolver=letsencrypt"

  # ==========================================
  # CLIENT PORTAL
  # Path: bizoholic.com/login/
  # ==========================================
  client-portal:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git
      dockerfile: frontend/apps/client-portal/Dockerfile
    container_name: bizosaas-client-portal-3001
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-unified:8001
      - NEXT_PUBLIC_SITE_URL=https://bizoholic.com/login
      - NEXT_PUBLIC_PORTAL_MODE=true
    networks:
      - bizosaas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portal.rule=Host(`bizoholic.com`) && PathPrefix(`/login`)"
      - "traefik.http.routers.portal.middlewares=portal-stripprefix"
      - "traefik.http.middlewares.portal-stripprefix.stripprefix.prefixes=/login"
      - "traefik.http.routers.portal.tls=true"
      - "traefik.http.routers.portal.tls.certresolver=letsencrypt"
      - "traefik.http.routers.portal.priority=10"

  # ==========================================
  # ADMIN DASHBOARD
  # Path: bizoholic.com/admin/
  # ==========================================
  admin-dashboard:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git
      dockerfile: frontend/apps/bizosaas-admin/Dockerfile
    container_name: bizosaas-admin-3009
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-unified:8001
      - NEXT_PUBLIC_SITE_URL=https://bizoholic.com/admin
      - NEXT_PUBLIC_ADMIN_MODE=true
    networks:
      - bizosaas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3009/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`bizoholic.com`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.admin.middlewares=admin-stripprefix"
      - "traefik.http.middlewares.admin-stripprefix.stripprefix.prefixes=/admin"
      - "traefik.http.routers.admin.tls=true"
      - "traefik.http.routers.admin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.admin.priority=10"

  # ==========================================
  # BUSINESS DIRECTORY (Existing)
  # Keep current configuration
  # ==========================================
  business-directory:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git
      dockerfile: frontend/apps/business-directory/Dockerfile
    container_name: business-directory-3004
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-unified:8001
    networks:
      - bizosaas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  bizosaas-network:
    external: true

# ==================================================
# DOMAIN SUMMARY:
# ==================================================
# bizoholic.com          → bizoholic-frontend (marketing)
# bizoholic.com/login/   → client-portal
# bizoholic.com/admin/   → admin-dashboard
# coreldove.com          → coreldove-frontend (e-commerce)
# thrillring.com         → thrillring-gaming (gaming)
# ==================================================