# BizOSaaS Backend Services - STAGING (Using GHCR Images)
# Proper workflow: Local → GHCR → GitHub → Dokploy
# Images pulled from GitHub Container Registry

services:
  # ==========================================
  # 1. BRAIN API - AI Gateway (Port 8001)
  # ==========================================
  brain-api:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/brain-api:staging
    container_name: bizosaas-brain-staging
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@194.238.16.237:5433/bizosaas_staging
      - REDIS_URL=redis://194.238.16.237:6380/0
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ENVIRONMENT=staging
      - LOG_LEVEL=INFO
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==========================================
  # 2. WAGTAIL CMS (Port 8002)
  # ==========================================
  wagtail-cms:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/wagtail-cms:staging
    container_name: bizosaas-wagtail-staging
    ports:
      - "8002:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=wagtail_cms.settings.production
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@194.238.16.237:5433/bizosaas_staging
      - REDIS_URL=redis://194.238.16.237:6380/3
      - SECRET_KEY=staging-secret-key-wagtail-bizosaas-2025
      - ALLOWED_HOSTS=194.238.16.237,localhost,stg.bizoholic.com
      - DEBUG=False
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # 3. DJANGO CRM (Port 8003)
  # ==========================================
  django-crm:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/django-crm:staging
    container_name: bizosaas-django-crm-staging
    ports:
      - "8003:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=crm_project.settings.production
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@194.238.16.237:5433/bizosaas_staging
      - REDIS_URL=redis://194.238.16.237:6380/4
      - SECRET_KEY=staging-secret-key-djangocrm-bizosaas-2025
      - ALLOWED_HOSTS=194.238.16.237,localhost,stg.bizoholic.com
      - DEBUG=False
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # 4. BUSINESS DIRECTORY BACKEND (Port 8004)
  # ==========================================
  business-directory-backend:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/business-directory-backend:staging
    container_name: bizosaas-business-directory-staging
    ports:
      - "8004:8000"
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@194.238.16.237:5433/bizosaas_staging
      - REDIS_URL=redis://194.238.16.237:6380/5
      - SECRET_KEY=staging-secret-key-bizdir-bizosaas-2025
      - ENVIRONMENT=staging
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # 5. CORELDOVE BACKEND (Port 8005)
  # ==========================================
  coreldove-backend:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/coreldove-backend:staging
    container_name: bizosaas-coreldove-backend-staging
    ports:
      - "8005:8000"
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@194.238.16.237:5433/bizosaas_staging
      - REDIS_URL=redis://194.238.16.237:6380/6
      - SECRET_KEY=staging-secret-key-coreldove-bizosaas-2025
      - ENVIRONMENT=staging
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # 6. AI AGENTS (Port 8008)
  # ==========================================
  ai-agents:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/ai-agents:staging
    container_name: bizosaas-ai-agents-staging
    ports:
      - "8008:8000"
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@194.238.16.237:5433/bizosaas_staging
      - REDIS_URL=redis://194.238.16.237:6380/8
      - BRAIN_API_URL=http://bizosaas-brain-staging:8001
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ENVIRONMENT=staging
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # 7. AMAZON SOURCING (Port 8009)
  # ==========================================
  amazon-sourcing:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/amazon-sourcing:staging
    container_name: bizosaas-amazon-sourcing-staging
    ports:
      - "8009:8000"
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@194.238.16.237:5433/bizosaas_staging
      - REDIS_URL=redis://194.238.16.237:6380/9
      - AMAZON_ACCESS_KEY=${AMAZON_ACCESS_KEY:-}
      - AMAZON_SECRET_KEY=${AMAZON_SECRET_KEY:-}
      - ENVIRONMENT=staging
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    external: true

# ==================================================
# PROPER WORKFLOW: Local → GHCR → GitHub → Dokploy
# ==================================================
# 1. Build images locally (test)
# 2. Push to GHCR (./setup-proper-workflow.sh)
# 3. Push this file to GitHub
# 4. Dokploy pulls from GHCR and deploys
#
# Benefits:
# - Fast deployment (pull image, not build)
# - Version controlled (GitHub)
# - Reliable (tested images)
# - Proper DevOps workflow
# ==================================================
