version: '3.8'

# BizOSaaS Frontend Applications - GitHub Source Build
# 6 Frontend application containers built from GitHub repository

services:
  # ==========================================
  # BIZOHOLIC MARKETING FRONTEND
  # Marketing website - BUILT FROM GITHUB
  # ==========================================
  bizoholic-frontend:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git#main
      dockerfile: frontend/apps/bizoholic-frontend/Dockerfile
    container_name: bizoholic-frontend-staging
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=staging
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_PUBLIC_SITE_URL=https://stg.bizoholic.com
      - NEXT_PUBLIC_ENVIRONMENT=staging
      - NEXT_PUBLIC_ENABLE_ANALYTICS=false
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/bizosaas_staging
    networks:
      - bizosaas-staging-network
    restart: unless-stopped
    labels:
      # Traefik routing for main domain
      - "traefik.enable=true"
      - "traefik.http.routers.bizoholic-staging-main.rule=Host(`stg.bizoholic.com`)"
      - "traefik.http.routers.bizoholic-staging-main.entrypoints=websecure"
      - "traefik.http.routers.bizoholic-staging-main.tls=true"
      - "traefik.http.routers.bizoholic-staging-main.tls.certresolver=letsencrypt"
      - "traefik.http.services.bizoholic-staging-main.loadbalancer.server.port=3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==========================================
  # CLIENT PORTAL
  # Client dashboard and portal - BUILT FROM GITHUB
  # ==========================================
  client-portal:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git#main
      dockerfile: frontend/apps/client-portal/Dockerfile
    container_name: client-portal-staging
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=staging
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_PUBLIC_SITE_URL=https://stg.bizoholic.com/login
      - NEXT_PUBLIC_ENVIRONMENT=staging
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/bizosaas_staging
    networks:
      - bizosaas-staging-network
    restart: unless-stopped
    labels:
      # Traefik routing for /login/ path
      - "traefik.enable=true"
      - "traefik.http.routers.client-portal-staging.rule=Host(`stg.bizoholic.com`) && PathPrefix(`/login`)"
      - "traefik.http.routers.client-portal-staging.entrypoints=websecure"
      - "traefik.http.routers.client-portal-staging.tls=true"
      - "traefik.http.routers.client-portal-staging.tls.certresolver=letsencrypt"
      - "traefik.http.routers.client-portal-staging.priority=2"
      - "traefik.http.middlewares.client-portal-stripprefix.stripprefix.prefixes=/login"
      - "traefik.http.routers.client-portal-staging.middlewares=client-portal-stripprefix"
      - "traefik.http.services.client-portal-staging.loadbalancer.server.port=3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==========================================
  # CORELDOVE E-COMMERCE FRONTEND
  # E-commerce storefront - BUILT FROM GITHUB
  # ==========================================
  coreldove-frontend:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git#main
      dockerfile: frontend/apps/coreldove-frontend/Dockerfile
    container_name: coreldove-frontend-staging
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=staging
      - NEXT_PUBLIC_API_BASE_URL=http://coreldove-backend-staging:8005
      - NEXT_PUBLIC_SALEOR_API_URL=http://bizosaas-saleor-staging:8000/graphql/
      - NEXT_PUBLIC_SITE_URL=https://stg.coreldove.com
      - NEXT_PUBLIC_ENVIRONMENT=staging
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
    networks:
      - bizosaas-staging-network
    restart: unless-stopped
    labels:
      # Traefik routing for CorelDove domain
      - "traefik.enable=true"
      - "traefik.http.routers.coreldove-staging.rule=Host(`stg.coreldove.com`)"
      - "traefik.http.routers.coreldove-staging.entrypoints=websecure"
      - "traefik.http.routers.coreldove-staging.tls=true"
      - "traefik.http.routers.coreldove-staging.tls.certresolver=letsencrypt"
      - "traefik.http.services.coreldove-staging.loadbalancer.server.port=3002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==========================================
  # BUSINESS DIRECTORY FRONTEND
  # Directory interface - BUILT FROM GITHUB
  # ==========================================
  business-directory:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git#main
      dockerfile: frontend/apps/business-directory/Dockerfile
    container_name: business-directory-staging
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=staging
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-directory-api-staging:8004
      - NEXT_PUBLIC_BRAIN_API_URL=http://bizosaas-brain-staging:8001
      - NEXT_PUBLIC_ENVIRONMENT=staging
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/bizosaas_staging
    networks:
      - bizosaas-staging-network
    restart: unless-stopped
    # No Traefik labels - internal testing only
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==========================================
  # THRILLRING GAMING PLATFORM
  # Gaming platform frontend - BUILT FROM GITHUB
  # ==========================================
  thrillring-gaming:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git#main
      dockerfile: frontend/apps/thrillring-gaming/Dockerfile
      args:
        - NODE_ENV=staging
    container_name: thrillring-gaming-staging
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=staging
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_PUBLIC_SITE_URL=https://stg.thrillring.com
      - NEXT_PUBLIC_ENVIRONMENT=staging
    networks:
      - bizosaas-staging-network
    restart: unless-stopped
    labels:
      # Traefik routing for ThrillRing domain
      - "traefik.enable=true"
      - "traefik.http.routers.thrillring-staging.rule=Host(`stg.thrillring.com`)"
      - "traefik.http.routers.thrillring-staging.entrypoints=websecure"
      - "traefik.http.routers.thrillring-staging.tls=true"
      - "traefik.http.routers.thrillring-staging.tls.certresolver=letsencrypt"
      - "traefik.http.services.thrillring-staging.loadbalancer.server.port=3005"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==========================================
  # ADMIN DASHBOARD
  # Administrative interface - BUILT FROM GITHUB
  # ==========================================
  admin-dashboard:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git#main
      dockerfile: frontend/apps/bizosaas-admin/Dockerfile
    container_name: admin-dashboard-staging
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=staging
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_PUBLIC_SITE_URL=https://stg.bizoholic.com/admin
      - NEXT_PUBLIC_ENVIRONMENT=staging
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/bizosaas_staging
    networks:
      - bizosaas-staging-network
    restart: unless-stopped
    labels:
      # Traefik routing for /admin/ path
      - "traefik.enable=true"
      - "traefik.http.routers.admin-dashboard-staging.rule=Host(`stg.bizoholic.com`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.admin-dashboard-staging.entrypoints=websecure"
      - "traefik.http.routers.admin-dashboard-staging.tls=true"
      - "traefik.http.routers.admin-dashboard-staging.tls.certresolver=letsencrypt"
      - "traefik.http.routers.admin-dashboard-staging.priority=3"
      - "traefik.http.middlewares.admin-dashboard-stripprefix.stripprefix.prefixes=/admin"
      - "traefik.http.routers.admin-dashboard-staging.middlewares=admin-dashboard-stripprefix"
      - "traefik.http.services.admin-dashboard-staging.loadbalancer.server.port=3009"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3009/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  bizosaas-staging-network:
    external: true

# ==================================================
# FRONTEND APPLICATIONS PROJECT SUMMARY:
# ==================================================
# Container Count: 6
# GitHub Build: All 6 services built from source
# Staging Domains:
#   - stg.bizoholic.com (Marketing + /login/ + /admin/)
#   - stg.coreldove.com (E-commerce)
#   - stg.thrillring.com (Gaming)
# SSL: Automatic Let's Encrypt certificates
# Dependencies: Backend services must be running
# ==================================================