# BizOSaaS Backend Services - STAGING Environment (Working Services Only)
# Starting with services that have verified requirements.txt files

services:
  # ==========================================
  # WAGTAIL CMS
  # Headless content management
  # ==========================================
  wagtail-cms:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git#main:bizosaas-platform/backend/services/cms
      dockerfile: Dockerfile
    container_name: bizosaas-wagtail-staging
    ports:
      - "8002:8002"
    environment:
      - DJANGO_SETTINGS_MODULE=wagtail_cms.settings.staging
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/bizosaas_staging
      - REDIS_URL=redis://bizosaas-redis-staging:6379/1
      - SECRET_KEY=${DJANGO_SECRET_KEY:-staging-wagtail-secret-key}
      - ALLOWED_HOSTS=stg.bizoholic.com,bizosaas-wagtail-staging
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # DJANGO CRM
  # Customer relationship management
  # ==========================================
  django-crm:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git#main:bizosaas-platform/backend/services/crm/django-crm
      dockerfile: Dockerfile
    container_name: bizosaas-django-crm-staging
    ports:
      - "8003:8003"
    environment:
      - DJANGO_SETTINGS_MODULE=django_crm.settings.staging
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/bizosaas_staging
      - REDIS_URL=redis://bizosaas-redis-staging:6379/2
      - SECRET_KEY=${DJANGO_CRM_SECRET_KEY:-staging-django-crm-secret-key}
      - ALLOWED_HOSTS=stg.bizoholic.com,bizosaas-django-crm-staging
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # SALEOR E-COMMERCE PLATFORM
  # Full-featured e-commerce API
  # ==========================================
  saleor-api:
    image: ghcr.io/saleor/saleor:3.20
    container_name: bizosaas-saleor-staging
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/saleor_staging
      - REDIS_URL=redis://bizosaas-redis-staging:6379/7
      - SECRET_KEY=${SALEOR_SECRET_KEY:-staging-saleor-secret-key-bizosaas-2025}
      - ALLOWED_HOSTS=stg.coreldove.com,bizosaas-saleor-staging,localhost
      - DEBUG=true
      - DEFAULT_FROM_EMAIL=noreply@stg.coreldove.com
      - CELERY_BROKER_URL=redis://bizosaas-redis-staging:6379/7
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    external: true

# ==================================================
# BACKEND SERVICES PROJECT SUMMARY (WORKING):
# ==================================================
# Container Count: 3 (verified working services)
# Purpose: Core backend for SaaS platform
# Services:
#   - Wagtail CMS (8002) - Content management (has requirements.txt)
#   - Django CRM (8003) - Customer management (has requirements.txt)
#   - Saleor API (8000) - E-commerce platform (pre-built image)
# Excluded:
#   - Brain API (build issues with requirements-simple.txt)
#   - Directory API (build context issues)
# Dependencies: Infrastructure (PostgreSQL, Redis, Vault)
# ==================================================
