# BizOSaaS Frontend Applications - STAGING Environment (Simplified)
# Starting with 3 core frontend services

services:
  # ==========================================
  # BIZOHOLIC MARKETING WEBSITE (STAGING)
  # Domain: stg.bizoholic.com
  # ==========================================
  bizoholic-frontend:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git#main:bizosaas/frontend/apps/bizoholic-frontend
      dockerfile: Dockerfile
    container_name: bizoholic-frontend-staging
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=staging
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-saleor-staging:8000
      - NEXT_PUBLIC_SITE_URL=https://stg.bizoholic.com
      - ENVIRONMENT=staging
      - DEBUG_MODE=true
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bizoholic-staging.rule=Host(`stg.bizoholic.com`)"
      - "traefik.http.routers.bizoholic-staging.tls=true"
      - "traefik.http.routers.bizoholic-staging.tls.certresolver=letsencrypt"
      - "traefik.http.services.bizoholic-staging.loadbalancer.server.port=3000"

  # ==========================================
  # CORELDOVE E-COMMERCE WEBSITE (STAGING)
  # Domain: stg.coreldove.com
  # ==========================================
  coreldove-frontend:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git#main:bizosaas/frontend/apps/coreldove-frontend
      dockerfile: Dockerfile
    container_name: coreldove-frontend-staging
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=staging
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-saleor-staging:8000
      - NEXT_PUBLIC_SITE_URL=https://stg.coreldove.com
      - NEXT_PUBLIC_SALEOR_API_URL=http://bizosaas-saleor-staging:8000/graphql/
      - ENVIRONMENT=staging
      - DEBUG_MODE=true
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coreldove-staging.rule=Host(`stg.coreldove.com`)"
      - "traefik.http.routers.coreldove-staging.tls=true"
      - "traefik.http.routers.coreldove-staging.tls.certresolver=letsencrypt"
      - "traefik.http.services.coreldove-staging.loadbalancer.server.port=3002"

  # ==========================================
  # THRILLRING GAMING WEBSITE (STAGING)
  # Domain: stg.thrillring.com
  # ==========================================
  thrillring-gaming:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git#main:bizosaas/frontend/apps/thrillring-gaming
      dockerfile: Dockerfile
    container_name: thrillring-gaming-staging
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=staging
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-saleor-staging:8000
      - NEXT_PUBLIC_SITE_URL=https://stg.thrillring.com
      - ENVIRONMENT=staging
      - DEBUG_MODE=true
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thrillring-staging.rule=Host(`stg.thrillring.com`)"
      - "traefik.http.routers.thrillring-staging.tls=true"
      - "traefik.http.routers.thrillring-staging.tls.certresolver=letsencrypt"
      - "traefik.http.services.thrillring-staging.loadbalancer.server.port=3003"

networks:
  dokploy-network:
    external: true

# ==================================================
# FRONTEND SERVICES PROJECT SUMMARY (SIMPLIFIED):
# ==================================================
# Container Count: 3 (core marketing and e-commerce sites)
# Purpose: Public-facing websites for staging
# External Access: Via Traefik reverse proxy with SSL
# Domains: stg.bizoholic.com, stg.coreldove.com, stg.thrillring.com
# Dependencies: Saleor API (backend)
# Build Context: Git repo with subdirectory context for each app
# ==================================================
