# BizOSaaS Frontend Applications - STAGING
# All 6 frontend services building directly from GitHub repository
# Deploy via Dokploy at dk.bizoholic.com

services:
  # ==========================================
  # 1. CLIENT PORTAL (Port 3006) - FIXED
  # ==========================================
  # FIX: Created missing TypeScript modules in GitHub repository
  client-portal:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/client-portal:staging
    pull_policy: always
    container_name: bizosaas-client-portal-staging
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://brain-gateway:8000
      - NEXT_PUBLIC_CRM_API_URL=http://bizosaas-django-crm-staging:8000
      - NEXT_PUBLIC_CMS_API_URL=http://bizosaas-wagtail-staging:8000
      - NEXT_PUBLIC_ECOM_API_URL=http://bizosaas-saleor-staging:8000
      - NEXT_PUBLIC_BRAIN_GATEWAY_URL=http://brain-gateway:8000
      - NEXT_PUBLIC_GRAPHQL_URL=https://api.bizoholic.net/graphql
      - NEXTAUTH_URL=https://app.bizoholic.net
      - NEXTAUTH_SECRET=bizosaas-client-portal-staging-secret-2025
      - NEXT_TELEMETRY_DISABLED=1
      # Authentik SSO Configuration
      - AUTHENTIK_ISSUER=https://sso.bizoholic.net/application/o/bizosaas/
      - AUTHENTIK_CLIENT_ID=${AUTHENTIK_CLIENT_ID}
      - AUTHENTIK_CLIENT_SECRET=${AUTHENTIK_CLIENT_SECRET}
    networks:
      - dokploy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client-portal.rule=Host(`app.bizoholic.net`)"
      - "traefik.http.routers.client-portal.entrypoints=websecure"
      - "traefik.http.routers.client-portal.tls.certresolver=letsencrypt"
      - "traefik.http.services.client-portal.loadbalancer.server.port=3000"

  # ==========================================
  # 2. BIZOHOLIC FRONTEND (Port 3007)
  # ==========================================
  bizoholic-frontend:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git#main:bizosaas-platform/frontend/apps/bizoholic-frontend
      dockerfile: Dockerfile
    container_name: bizosaas-bizoholic-frontend-staging
    ports:
      - "3007:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_PUBLIC_CMS_API_URL=http://bizosaas-wagtail-staging:8000
      - NEXT_PUBLIC_CRM_API_URL=http://bizosaas-django-crm-staging:8000
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - dokploy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bizoholic-frontend.rule=Host(`www.bizoholic.net`)"
      - "traefik.http.routers.bizoholic-frontend.entrypoints=websecure"
      - "traefik.http.routers.bizoholic-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.bizoholic-frontend.loadbalancer.server.port=3000"

  # ==========================================
  # 3. CORELDOVE FRONTEND (Port 3008)
  # ==========================================
  coreldove-frontend:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git#main:bizosaas-platform/frontend/apps/coreldove-frontend
      dockerfile: Dockerfile
    container_name: bizosaas-coreldove-frontend-staging
    ports:
      - "3008:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_PUBLIC_SALEOR_API_URL=http://bizosaas-saleor-staging:8000/graphql/
      - NEXT_PUBLIC_CORELDOVE_BACKEND_URL=http://bizosaas-coreldove-backend-staging:8000
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - dokploy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coreldove-frontend.rule=Host(`coreldove.bizoholic.net`)"
      - "traefik.http.routers.coreldove-frontend.entrypoints=websecure"
      - "traefik.http.routers.coreldove-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.coreldove-frontend.loadbalancer.server.port=3000"

  # ==========================================
  # 4. BUSINESS DIRECTORY FRONTEND (Port 3009)
  # ==========================================
  business-directory-frontend:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git#main:bizosaas-platform/frontend/apps/business-directory
      dockerfile: Dockerfile
    container_name: bizosaas-business-directory-frontend-staging
    ports:
      - "3009:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_PUBLIC_DIRECTORY_API_URL=http://bizosaas-business-directory-staging:8000
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - dokploy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.business-directory.rule=Host(`directory.bizoholic.net`)"
      - "traefik.http.routers.business-directory.entrypoints=websecure"
      - "traefik.http.routers.business-directory.tls.certresolver=letsencrypt"
      - "traefik.http.services.business-directory.loadbalancer.server.port=3000"

  # ==========================================
  # 5. THRILLRING GAMING (Port 3010) - FIXED
  # ==========================================
  # FIX: Created thrillring-gaming app directory in GitHub repository
  thrillring-gaming:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git#main:bizosaas-platform/frontend/apps/thrillring-gaming
      dockerfile: Dockerfile
    container_name: bizosaas-thrillring-gaming-staging
    ports:
      - "3010:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - dokploy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thrillring-gaming.rule=Host(`gaming.bizoholic.net`)"
      - "traefik.http.routers.thrillring-gaming.entrypoints=websecure"
      - "traefik.http.routers.thrillring-gaming.tls.certresolver=letsencrypt"
      - "traefik.http.services.thrillring-gaming.loadbalancer.server.port=3000"

  # ==========================================
  # 6. BIZOSAAS ADMIN DASHBOARD (Port 3011)
  # ==========================================
  admin-dashboard:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/admin-dashboard:staging
    pull_policy: always
    container_name: bizosaas-admin-dashboard-staging
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_PUBLIC_SUPERSET_URL=http://bizosaas-superset-staging:8088
      - NEXT_PUBLIC_TEMPORAL_UI_URL=http://bizosaas-temporal-ui-staging:8080
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - dokploy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin-dashboard.rule=Host(`admin.bizoholic.net`)"
      - "traefik.http.routers.admin-dashboard.entrypoints=websecure"
      - "traefik.http.routers.admin-dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.services.admin-dashboard.loadbalancer.server.port=3000"

networks:
  dokploy-network:
    external: true
