version: "3.9"
services:
  # ==========================================
  # 1. CLIENT PORTAL (Port 3000)
  # ==========================================
  client-portal:
    build:
      context: ./source/portals/client-portal
      dockerfile: Dockerfile
    container_name: bizosaas-client-portal-staging
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_PUBLIC_CRM_API_URL=http://bizosaas-django-crm-staging:8000
      - NEXT_PUBLIC_CMS_API_URL=http://bizosaas-wagtail-staging:8000
      - NEXT_PUBLIC_ECOM_API_URL=http://bizosaas-saleor-staging:8000
      - NEXT_PUBLIC_BRAIN_GATEWAY_URL=https://api.bizoholic.net
      - NEXT_PUBLIC_GRAPHQL_URL=https://api.bizoholic.net/graphql
      - NEXTAUTH_URL=https://app.bizoholic.net
      - NEXTAUTH_SECRET=bizosaas-client-portal-staging-secret-2025
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  dokploy-network:
    external: true
