# BizOSaaS Frontend Applications - STAGING (Using GHCR Images)
# Proper workflow: Local → GHCR → GitHub → Dokploy

services:
  # ==========================================
  # 1. CLIENT PORTAL (Port 3000)
  # ==========================================
  client-portal:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/client-portal:staging
    container_name: bizosaas-client-portal-staging
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # 2. BIZOHOLIC FRONTEND (Port 3001)
  # ==========================================
  bizoholic-frontend:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/bizoholic-frontend:staging
    container_name: bizosaas-bizoholic-frontend-staging
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # 3. CORELDOVE FRONTEND (Port 3002)
  # ==========================================
  coreldove-frontend:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/coreldove-frontend:staging
    container_name: bizosaas-coreldove-frontend-staging
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # 4. BUSINESS DIRECTORY FRONTEND (Port 3003)
  # ==========================================
  business-directory-frontend:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/business-directory-frontend:staging
    container_name: bizosaas-business-directory-frontend-staging
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # 5. ADMIN DASHBOARD (Port 3005)
  # ==========================================
  admin-dashboard:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/admin-dashboard:staging
    container_name: bizosaas-admin-dashboard-staging
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    external: true

# ==================================================
# PROPER WORKFLOW: Local → GHCR → GitHub → Dokploy
# ==================================================
