# BizOSaaS Frontend Applications - STAGING (Using Local Pre-Built Images)
# Working local images transferred directly to VPS
# Deploy via Dokploy at dk.bizoholic.com

services:
  # ==========================================
  # 1. CLIENT PORTAL (Port 3000)
  # ==========================================
  client-portal:
    image: bizosaas-client-portal:latest
    container_name: bizosaas-client-portal-staging
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # 2. BIZOHOLIC FRONTEND (Port 3001)
  # ==========================================
  bizoholic-frontend:
    image: bizosaas-bizoholic-frontend:latest
    container_name: bizosaas-bizoholic-frontend-staging
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # 3. CORELDOVE FRONTEND (Port 3002)
  # ==========================================
  coreldove-frontend:
    image: bizosaas-coreldove-frontend:latest
    container_name: bizosaas-coreldove-frontend-staging
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # 4. BUSINESS DIRECTORY FRONTEND (Port 3003)
  # ==========================================
  business-directory-frontend:
    image: bizosaas-business-directory:latest
    container_name: bizosaas-business-directory-frontend-staging
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - dokploy-network
    restart: unless-stopped

  # ==========================================
  # 5. ADMIN DASHBOARD (Port 3005)
  # ==========================================
  admin-dashboard:
    image: bizosaas-bizosaas-admin:latest
    container_name: bizosaas-admin-dashboard-staging
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    external: true

# ==================================================
# DEPLOYMENT STRATEGY: Local Pre-Built Images
# ==================================================
# These images are already built and tested locally
# They have been transferred to VPS via docker save/load
# No GitHub build required - images ready to deploy
# ==================================================
