version: "3.8"
services:
  bizoholic-frontend:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/bizoholic-frontend:staging
    pull_policy: always
    container_name: bizosaas-frontend-staging
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.bizoholic.net
    networks:
      - dokploy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 384M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bizoholic-fe.rule=Host(`stg.bizoholic.com`)"
      - "traefik.http.routers.bizoholic-fe.entrypoints=websecure"
      - "traefik.http.routers.bizoholic-fe.tls.certresolver=letsencrypt"
      - "traefik.http.services.bizoholic-fe.loadbalancer.server.port=3000"

  client-portal:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/client-portal:staging
    pull_policy: always
    container_name: bizosaas-client-portal-staging
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=https://api.bizoholic.net
      - NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${NEXT_PUBLIC_STRIPE_PUBLIC_KEY}
      - NEXTAUTH_URL=https://stg.bizoholic.com/login
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - AUTHENTIK_ISSUER=${AUTHENTIK_ISSUER}
      - AUTHENTIK_CLIENT_ID=${AUTHENTIK_CLIENT_ID}
      - AUTHENTIK_CLIENT_SECRET=${AUTHENTIK_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - BRAIN_GATEWAY_URL=http://brain-gateway:8000
    networks:
      - dokploy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 512M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client-portal.rule=Host(`stg.bizoholic.com`) && PathPrefix(`/login`)"
      - "traefik.http.routers.client-portal.entrypoints=websecure"
      - "traefik.http.routers.client-portal.tls.certresolver=letsencrypt"
      - "traefik.http.services.client-portal.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.client-portal-strip.stripprefix.prefixes=/login"
      # Apply stripprefix middleware to router
      - "traefik.http.routers.client-portal.middlewares=client-portal-strip"

  coreldove-frontend:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/coreldove-frontend:staging
    pull_policy: always
    container_name: bizosaas-coreldove-staging
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SALEOR_API_URL=https://api.coreldove.com/graphql
    networks:
      - dokploy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 384M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coreldove-fe.rule=Host(`stg.coreldove.com`)"
      - "traefik.http.routers.coreldove-fe.entrypoints=websecure"
      - "traefik.http.routers.coreldove-fe.tls.certresolver=letsencrypt"
      - "traefik.http.services.coreldove-fe.loadbalancer.server.port=3000"

  business-directory-frontend:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/business-directory-frontend:staging
    pull_policy: always
    container_name: bizosaas-directory-fe-staging
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://business-directory-backend:8000
    networks:
      - dokploy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    labels:
      # Internal service for now, or expose if needed
      - "traefik.enable=false"

  thrillring-gaming:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/thrillring-gaming:staging
    pull_policy: always
    container_name: bizosaas-thrillring-staging
    environment:
      - NODE_ENV=production
      - PORT=3007
    networks:
      - dokploy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thrillring-fe.rule=Host(`thrillring.com`) || Host(`www.thrillring.com`) || Host(`stg.thrillring.com`)"
      - "traefik.http.routers.thrillring-fe.entrypoints=websecure"
      - "traefik.http.routers.thrillring-fe.tls=true"
      - "traefik.http.routers.thrillring-fe.tls.certresolver=letsencrypt"
      - "traefik.http.services.thrillring-fe.loadbalancer.server.port=3007"

  admin-dashboard:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/admin-dashboard:staging
    pull_policy: always
    container_name: bizosaas-admin-dashboard-staging
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=https://api.bizoholic.net
      - NEXT_PUBLIC_SUPERSET_URL=http://bizosaas-superset-staging:8088
      - NEXT_PUBLIC_TEMPORAL_UI_URL=http://bizosaas-temporal-ui-staging:8080
      - NEXT_TELEMETRY_DISABLED=1
      - AUTH_SERVICE_URL=http://auth-service:8006
      - NEXTAUTH_URL=https://stg.bizoholic.com/admin
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-}
      - AUTHENTIK_ISSUER=${AUTHENTIK_ISSUER}
      - AUTHENTIK_CLIENT_ID=${AUTHENTIK_CLIENT_ID}
      - AUTHENTIK_CLIENT_SECRET=${AUTHENTIK_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - VAULT_ADDR=${VAULT_URL}
      - VAULT_TOKEN=${VAULT_TOKEN:-}
      - VAULT_SECRET_PATH=${VAULT_SECRET_PATH:-bizosaas/stg/admin-dashboard}
      - VAULT_MOUNT_POINT=${VAULT_MOUNT_POINT:-secret}
    networks:
      - dokploy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 512M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin-dashboard.rule=Host(`stg.bizoholic.com`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.admin-dashboard.entrypoints=websecure"
      - "traefik.http.routers.admin-dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.services.admin-dashboard.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.admin-strip.stripprefix.prefixes=/admin"
      - "traefik.http.routers.admin-dashboard.middlewares=admin-strip"

networks:
  dokploy-network:
    external: true
