# BizOSaaS Frontend Applications - STAGING
# All 6 frontend services building directly from GitHub repository
# Deploy via Dokploy at dk.bizoholic.com

services:
  # ==========================================
  # 1. CLIENT PORTAL (Port 3006) - FIXED
  # ==========================================
  # FIX: Created missing TypeScript modules in GitHub repository
  client-portal:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/client-portal:staging
    pull_policy: always
    container_name: bizosaas-client-portal-staging
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://brain-gateway:8000
      - NEXT_PUBLIC_CRM_API_URL=http://bizosaas-django-crm-staging:8000
      - NEXT_PUBLIC_CMS_API_URL=http://bizosaas-wagtail-staging:8000
      - NEXT_PUBLIC_ECOM_API_URL=http://bizosaas-saleor-staging:8000
      - NEXT_PUBLIC_BRAIN_GATEWAY_URL=https://api.bizoholic.net
      - NEXT_PUBLIC_GRAPHQL_URL=https://api.bizoholic.net/graphql
      - NEXTAUTH_URL=https://app.bizoholic.net
      - NEXTAUTH_SECRET=vc+i1safx5PvOaK9gc6PYLwetF4UFFWX/exE+OtzNP0=
      - NEXT_TELEMETRY_DISABLED=1
      # Authentik SSO Configuration
      - AUTHENTIK_ISSUER=https://sso.bizoholic.net/application/o/bizosaas/
      - AUTHENTIK_CLIENT_ID=Tib8uZl1hqA5WXDxLFnl32MSbOkmISJ3GBUsOate
      - AUTHENTIK_CLIENT_SECRET=RQTn62rsx7SmKcXFFcT6nb2E4gaZS1DIBTi4XhboQV8Mxm6ygQFBEaEnQf1IYI08oezj4B3vXmNSoadpn3QxtzopEojtLVCDgSxMBUBtnIAyOfqZcwmKWiMejqlKEasp
    networks:
      - dokploy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client-portal.rule=Host(`app.bizoholic.net`)"
      - "traefik.http.routers.client-portal.entrypoints=websecure"
      - "traefik.http.routers.client-portal.tls.certresolver=letsencrypt"
      - "traefik.http.services.client-portal.loadbalancer.server.port=3000"

  # ==========================================
  # 2. BIZOSAAS ADMIN DASHBOARD (Port 3011)
  # ==========================================
  admin-dashboard:
    image: ghcr.io/bizoholic-digital/bizosaas-platform/admin-dashboard:staging
    pull_policy: always
    container_name: bizosaas-admin-dashboard-staging
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://bizosaas-brain-staging:8001
      - NEXT_PUBLIC_SUPERSET_URL=http://bizosaas-superset-staging:8088
      - NEXT_PUBLIC_TEMPORAL_UI_URL=http://bizosaas-temporal-ui-staging:8080
      - NEXT_TELEMETRY_DISABLED=1
      # NextAuth & Authentik SSO Configuration
      - NEXTAUTH_URL=https://admin.bizoholic.net
      - NEXTAUTH_SECRET=vc+i1safx5PvOaK9gc6PYLwetF4UFFWX/exE+OtzNP0=
      - AUTHENTIK_ISSUER=https://sso.bizoholic.net/application/o/bizosaas/
      - AUTHENTIK_CLIENT_ID=bizosaas-admin-dashboard
      - AUTHENTIK_CLIENT_SECRET=RQTn62rsx7SmKcXFFcT6nb2E4gaZS1DIBTi4XhboQV8Mxm6ygQFBEaEnQf1IYI08oezj4B3vXmNSoadpn3QxtzopEojtLVCDgSxMBUBtnIAyOfqZcwmKWiMejqlKEasp
    networks:
      - dokploy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin-dashboard.rule=Host(`admin.bizoholic.net`)"
      - "traefik.http.routers.admin-dashboard.entrypoints=websecure"
      - "traefik.http.routers.admin-dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.services.admin-dashboard.loadbalancer.server.port=3000"

networks:
  dokploy-network:
    external: true
