# BizOSaaS Backend Services - STAGING Environment (Stable Build)
# Services with verified successful builds

services:
  # ==========================================
  # BRAIN API - AI Central Hub
  # Main API coordinator for all services
  # ==========================================
  brain-api:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git#main:bizosaas-platform/ai/services/bizosaas-brain
      dockerfile: Dockerfile
    container_name: bizosaas-brain-staging
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=staging
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/bizosaas_staging
      - REDIS_URL=redis://bizosaas-redis-staging:6379/0
      - VAULT_ADDR=http://bizosaas-vault-staging:8200
      - VAULT_TOKEN=staging-root-token-bizosaas-2025
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-sk-or-v1-default}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-proj-default}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-sk-ant-default}
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==========================================
  # WAGTAIL CMS
  # Headless content management
  # ==========================================
  wagtail-cms:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git#main:bizosaas-platform/backend/services/cms
      dockerfile: Dockerfile
    container_name: bizosaas-wagtail-staging
    ports:
      - "8002:8002"
    environment:
      - DJANGO_SETTINGS_MODULE=wagtail_cms.settings.staging
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/bizosaas_staging
      - REDIS_URL=redis://bizosaas-redis-staging:6379/1
      - SECRET_KEY=${DJANGO_SECRET_KEY:-staging-wagtail-secret-key-bizosaas-2025}
      - ALLOWED_HOSTS=stg.bizoholic.com,bizosaas-wagtail-staging
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==========================================
  # DJANGO CRM
  # Customer relationship management
  # ==========================================
  django-crm:
    build:
      context: https://github.com/Bizoholic-Digital/bizosaas-platform.git#main:bizosaas-platform/backend/services/crm/django-crm
      dockerfile: Dockerfile
    container_name: bizosaas-django-crm-staging
    ports:
      - "8003:8003"
    environment:
      - DJANGO_SETTINGS_MODULE=django_crm.settings.staging
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/bizosaas_staging
      - REDIS_URL=redis://bizosaas-redis-staging:6379/2
      - SECRET_KEY=${DJANGO_CRM_SECRET_KEY:-staging-django-crm-secret-key-bizosaas-2025}
      - ALLOWED_HOSTS=stg.bizoholic.com,bizosaas-django-crm-staging
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==========================================
  # SALEOR E-COMMERCE PLATFORM
  # Full-featured e-commerce API
  # ==========================================
  saleor-api:
    image: ghcr.io/saleor/saleor:3.20
    container_name: bizosaas-saleor-staging
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:BizOSaaS2025!StagingDB@bizosaas-postgres-staging:5432/saleor_staging
      - REDIS_URL=redis://bizosaas-redis-staging:6379/7
      - SECRET_KEY=${SALEOR_SECRET_KEY:-staging-saleor-secret-key-bizosaas-2025}
      - ALLOWED_HOSTS=stg.coreldove.com,bizosaas-saleor-staging,localhost
      - DEBUG=true
      - DEFAULT_FROM_EMAIL=noreply@stg.coreldove.com
      - CELERY_BROKER_URL=redis://bizosaas-redis-staging:6379/7
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  dokploy-network:
    external: true

# ==================================================
# BACKEND SERVICES PROJECT SUMMARY (STABLE):
# ==================================================
# Container Count: 4 (successfully built services)
# Purpose: Complete backend for SaaS platform
# Services:
#   - Brain API (8001) - AI coordinator ✅ BUILT
#   - Wagtail CMS (8002) - Content management ✅ BUILT
#   - Django CRM (8003) - Customer management ✅ BUILT
#   - Saleor API (8000) - E-commerce platform ✅ PRE-BUILT
# Excluded:
#   - Directory API - dependency conflict with pydantic-settings
# Dependencies: Infrastructure (PostgreSQL, Redis, Vault)
# ==================================================
