version: '3.4'

services:
  api:
    ports:
      - "8024:8000"
    environment:
      - DATABASE_URL=postgres://saleor:saleor@db:5432/saleor
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=changeme
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DEFAULT_FROM_EMAIL=noreply@coreldove.com
      - ENABLE_DEBUG_TOOLBAR=True
      - INTERNAL_IPS=127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:3001,http://localhost:3000
      - CORS_ALLOW_ALL_ORIGINS=True
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=saleor
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
    volumes:
      - saleor_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - saleor_redis:/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://saleor:saleor@db:5432/saleor
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=changeme
    command: celery -A saleor worker --loglevel=info
    depends_on:
      - db
      - redis

volumes:
  saleor_db:
  saleor_redis: