<?php
/**
 * Do not edit this file. Edit the config files found in the config/ directory instead.
 * This file is required to load the WordPress configuration.
 *
 * @package Bedrock
 */

/** @var string Directory containing all of the site's files */
$root_dir = dirname(__DIR__);

/**
 * Load Vendor Autoloader
 */
require_once $root_dir . '/vendor/autoload.php';

/**
 * Load Application Configuration
 */
require_once $root_dir . '/config/application.php';

/**
 * Bootstrap WordPress
 */
require_once ABSPATH . 'wp-settings.php';
