version: '3.8'

services:
  bizosaas-auth-unified:
    build: 
      context: .
      dockerfile: Dockerfile
    image: bizosaas-auth-unified:latest
    container_name: bizosaas-auth-unified
    restart: unless-stopped
    ports:
      - "8007:8007"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:${POSTGRES_PASSWORD:-Bizoholic2024Alagiri}@bizosaas-postgres-unified:5432/bizosaas
      - REDIS_URL=redis://bizosaas-redis-unified:6379/0
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS:-30}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - PORT=8007
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:3001,http://localhost:3002,http://localhost:3003,http://localhost:3004,https://bizoholic.com,https://coreldove.com,https://app.bizosaas.com}
    networks:
      - bizosaas-platform-network
    depends_on:
      - bizosaas-postgres-unified
      - bizosaas-redis-unified
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.bizosaas.local`) || PathPrefix(`/auth`)"
      - "traefik.http.routers.auth.tls=true"
      - "traefik.http.services.auth.loadbalancer.server.port=8007"
      - "traefik.docker.network=bizosaas-platform-network"

networks:
  bizosaas-platform-network:
    external: true

volumes:
  auth_logs:
    driver: local