# Temporal.io Development Configuration
# Optimized for AI workflow orchestration and multi-tenant SaaS

system.forceSearchAttributesCacheRefreshOnRead:
  - value: true
    constraints: {}

system.searchAttributesNumberOfKeysLimit:
  - value: 100
    constraints: {}

system.searchAttributesSizeOfValueLimit:
  - value: 40000
    constraints: {}

system.searchAttributesTotalSizeLimit:
  - value: 40000
    constraints: {}

system.blobSizeLimitError:
  - value: 2000000
    constraints: {}

system.blobSizeLimitWarn:
  - value: 512000
    constraints: {}

system.historyMaxPageSize:
  - value: 1000
    constraints: {}

system.rps:
  - value: 3000
    constraints: {}

system.maxIDLengthLimit:
  - value: 1000
    constraints: {}

frontend.rps:
  - value: 2400
    constraints: {}

frontend.globalNamespaceRPS:
  - value: 1200
    constraints: {}

history.rps:
  - value: 3000
    constraints: {}

history.persistenceMaxQPS:
  - value: 9000
    constraints: {}

matching.rps:
  - value: 3000
    constraints: {}

worker.rps:
  - value: 2400
    constraints: {}

# AI Workflow specific settings
system.enableActivityEagerExecution:
  - value: true
    constraints: {}

system.enableEagerWorkflowStart:
  - value: true
    constraints: {}

# Multi-tenant support
frontend.namespaceCountLimitPerInstance:
  - value: 1200
    constraints: {}

# Development friendly settings
system.enableDebugMode:
  - value: true
    constraints: {}

system.enableLoggingInReplication:
  - value: true
    constraints: {}