#!/bin/bash

# BizOSaaS Infrastructure Services Startup Script
echo "🏗️ Starting BizOSaaS Infrastructure Services..."

# Start infrastructure services
echo "🔧 Starting infrastructure with Docker Compose..."
docker-compose -f docker-compose.infrastructure.yml up -d

echo ""
echo "⏳ Waiting for services to be ready..."
sleep 10

echo ""
echo "🎉 Infrastructure services started!"
echo ""
echo "🌐 Infrastructure Service Access URLs:"
echo "┌─────────────────────────────────────────────────────────────┐"
echo "│ INFRASTRUCTURE DASHBOARDS                                   │"
echo "├─────────────────────────────────────────────────────────────┤"
echo "│ 🔒 HashiCorp Vault       → http://localhost:8200            │"
echo "│    Token: myroot                                            │"
echo "│                                                             │"
echo "│ ⏰ Temporal Web UI        → http://localhost:8080            │"
echo "│                                                             │"
echo "│ 🔀 Traefik Dashboard     → http://localhost:8090            │"
echo "│                                                             │"
echo "│ 🗄️ PostgreSQL (pgAdmin)   → http://localhost:5050            │"
echo "│    Email: admin@bizoholic.com                               │"
echo "│    Password: SharedPgAdmin2024!Secure                       │"
echo "│                                                             │"
echo "│ 📦 MinIO Console          → http://localhost:9001            │"
echo "│    Username: bizosaas                                       │"
echo "│    Password: SharedInfra2024!SuperSecure                    │"
echo "└─────────────────────────────────────────────────────────────┘"
echo ""
echo "🔌 Database Connections:"
echo "┌─────────────────────────────────────────────────────────────┐"
echo "│ 🐘 Main PostgreSQL       → localhost:5434                   │"
echo "│    Database: bizosaas                                       │"
echo "│    User: postgres                                           │"
echo "│    Password: SharedInfra2024!SuperSecure                    │"
echo "│                                                             │"
echo "│ ⏰ Temporal PostgreSQL    → localhost:5433                   │"
echo "│    Database: temporal                                       │"
echo "│    User: temporal                                           │"
echo "│    Password: temporal                                       │"
echo "│                                                             │"
echo "│ 🔥 Dragonfly (Redis)      → localhost:6379                  │"
echo "│                                                             │"
echo "│ 📦 MinIO S3 API          → localhost:9000                   │"
echo "└─────────────────────────────────────────────────────────────┘"
echo ""
echo "🛑 Stop Infrastructure:"
echo "docker-compose -f docker-compose.infrastructure.yml down"