http:
  routers:
    # HTTP to HTTPS redirect
    frontend-bizoholic-frontend-router-2:
      rule: Host(`stg.bizoholic.com`)
      service: frontend-bizoholic-frontend-service-2
      middlewares:
        - redirect-to-https
      entryPoints:
        - web
    
    # Main frontend HTTPS router
    frontend-bizoholic-frontend-router-websecure-2:
      rule: Host(`stg.bizoholic.com`) && !PathPrefix(`/api/`)
      service: frontend-bizoholic-frontend-service-2
      priority: 10
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    
    # API requests proxy to brain-gateway
    frontend-bizoholic-api-router:
      rule: Host(`stg.bizoholic.com`) && PathPrefix(`/api/`)
      service: brain-gateway-service
      priority: 20
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    frontend-bizoholic-frontend-service-2:
      loadBalancer:
        servers:
          - url: http://frontend-bizoholic-frontend:3000
        passHostHeader: true
    
    brain-gateway-service:
      loadBalancer:
        servers:
          - url: http://backend-brain-gateway:8001
        passHostHeader: true
