version: '3.8'

services:
  commerce-advisor-ai:
    build: .
    container_name: bizosaas-commerce-advisor-ai
    ports:
      - "8030:8030"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/bizosaas
      - REDIS_URL=redis://redis:6379
      - BRAIN_API_URL=http://brain-api:8001
      - CORELDOVE_API_URL=http://coreldove-frontend:3012
      - SALEOR_API_URL=http://saleor-api:8000/graphql/
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
      - GOOGLE_ANALYTICS_KEY=${GOOGLE_ANALYTICS_KEY}
      - FACEBOOK_PIXEL_KEY=${FACEBOOK_PIXEL_KEY}
      - RAZORPAY_KEY=${RAZORPAY_KEY}
      - PAYU_KEY=${PAYU_KEY}
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
      - ./models:/app/models
      - commerce-advisor-data:/app/data
    depends_on:
      - postgres
      - redis
    networks:
      - bizosaas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8030/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    container_name: bizosaas-commerce-postgres
    environment:
      - POSTGRES_DB=bizosaas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-commerce-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - bizosaas-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: bizosaas-commerce-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-commerce-data:/data
    networks:
      - bizosaas-network
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru

volumes:
  postgres-commerce-data:
    driver: local
  redis-commerce-data:
    driver: local
  commerce-advisor-data:
    driver: local

networks:
  bizosaas-network:
    external: true