apiVersion: 1

datasources:
  # Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s

  # Elasticsearch datasource
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[bizosaas_*]YYYY.MM.DD"
    editable: true
    jsonData:
      timeField: timestamp
      esVersion: "8.11.0"
      interval: Daily
      logMessageField: message
      logLevelField: level
