# Grafana datasource configuration for BizOSaaS Platform
apiVersion: 1

datasources:
  # Primary Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: '15s'
      queryTimeout: '60s'
      httpMethod: 'POST'
    editable: true
    
  # Elasticsearch for logs
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: 'logstash-*'
    jsonData:
      interval: Daily
      timeField: '@timestamp'
      esVersion: '8.6.0'
      maxConcurrentShardRequests: 5
      logMessageField: 'message'
      logLevelField: 'level'
    editable: true

  # Jaeger for distributed tracing  
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    jsonData:
      tracesToLogs:
        datasourceUid: 'elasticsearch'
        filterBySpanID: false
        filterByTraceID: true
        mapTagNamesEnabled: true
        tags: ['service.name', 'service.version']
      tracesToMetrics:
        datasourceUid: 'prometheus'
        tags: [{ key: 'service.name', value: 'service' }]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(traces_spanmetrics_calls_total{$$__tags}[5m]))'
      nodeGraph:
        enabled: true
    editable: true

  # Loki for log aggregation (if using Loki instead of Elasticsearch)
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: 'traceID=(\\w+)'
          name: TraceID
          url: '$${__value.raw}'
    editable: true

  # PostgreSQL for business metrics
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: bizosaas-postgres-unified:5432
    database: bizosaas
    user: postgres
    secureJsonData:
      password: Bizoholic2024Alagiri
    jsonData:
      sslmode: disable
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    editable: true

  # TestData for dashboard development
  - name: TestData
    type: testdata
    access: proxy
    isDefault: false
    editable: false