# Generated by Django 4.2.24 on 2025-09-09 16:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCustomField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'Date Time'), ('boolean', 'Yes/No'), ('select', 'Dropdown'), ('multi_select', 'Multi Select'), ('url', 'URL'), ('email', 'Email')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.TextField(blank=True)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select/multi_select fields')),
                ('help_text', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'leads_custom_field',
                'ordering': ['order', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LeadTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'leads_tag',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Conversion rate percentage', max_digits=5)),
                ('total_leads', models.IntegerField(default=0)),
                ('converted_leads', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'leads_source',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('company_website', models.URLField(blank=True)),
                ('company_size', models.CharField(blank=True, max_length=50)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated annual revenue', max_digits=15, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('negotiation', 'In Negotiation'), ('converted', 'Converted'), ('lost', 'Lost'), ('unresponsive', 'Unresponsive')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('score', models.IntegerField(default=0, help_text='AI-generated lead score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_factors', models.JSONField(blank=True, default=dict, help_text='Factors contributing to the lead score')),
                ('last_scored_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the lead')),
                ('first_contact_date', models.DateTimeField(blank=True, null=True)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_term', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('referrer', models.URLField(blank=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated budget', max_digits=12, null=True)),
                ('timeline', models.CharField(blank=True, help_text='Expected timeline', max_length=100)),
                ('decision_maker', models.BooleanField(default=False, help_text='Is this person a decision maker?')),
                ('pain_points', models.TextField(blank=True, help_text='Identified pain points')),
                ('requirements', models.TextField(blank=True, help_text='Business requirements')),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, help_text='Value of conversion', max_digits=12, null=True)),
                ('lost_reason', models.TextField(blank=True, help_text='Reason if lead was lost')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User responsible for this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, help_text='How the lead was acquired', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadsource')),
                ('tags', models.ManyToManyField(blank=True, related_name='leads', to='leads.leadtag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'leads_lead',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False, help_text='Private note visible only to author')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_notes', to='leads.lead')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leads_note',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'lead'], name='leads_note_tenant__b5d247_idx'), models.Index(fields=['created_at'], name='leads_note_created_ac775f_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadCustomFieldValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leadcustomfield')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='leads.lead')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'leads_custom_field_value',
                'unique_together': {('lead', 'custom_field')},
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('note', 'Note Added'), ('email', 'Email Sent'), ('call', 'Phone Call'), ('meeting', 'Meeting'), ('contact', 'First Contact'), ('follow_up', 'Follow Up'), ('proposal', 'Proposal Sent'), ('convert', 'Converted'), ('lost', 'Marked as Lost'), ('status_change', 'Status Changed'), ('assignment', 'Assignment Changed')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leads_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'lead'], name='leads_activ_tenant__b5c809_idx'), models.Index(fields=['tenant', 'user'], name='leads_activ_tenant__099cf3_idx'), models.Index(fields=['tenant', 'activity_type'], name='leads_activ_tenant__3d9d7c_idx'), models.Index(fields=['created_at'], name='leads_activ_created_de4f8f_idx'), models.Index(fields=['scheduled_at'], name='leads_activ_schedul_d1ef68_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'status'], name='leads_lead_tenant__054659_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'assigned_to'], name='leads_lead_tenant__bf2f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'score'], name='leads_lead_tenant__f00a09_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'priority'], name='leads_lead_tenant__dcee45_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'source'], name='leads_lead_tenant__850269_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='leads_lead_email_f663dc_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company'], name='leads_lead_company_8dadd2_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='leads_lead_created_302c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_follow_up'], name='leads_lead_next_fo_b18d27_idx'),
        ),
    ]
