version: '3.8'

services:
  marketing-strategist-ai:
    build: .
    container_name: bizosaas-marketing-strategist-ai
    ports:
      - "8029:8029"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/bizosaas
      - REDIS_URL=redis://redis:6379
      - BRAIN_API_URL=http://brain-api:8001
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GOOGLE_ADS_API_KEY=${GOOGLE_ADS_API_KEY:-}
      - META_ADS_API_KEY=${META_ADS_API_KEY:-}
      - LINKEDIN_ADS_API_KEY=${LINKEDIN_ADS_API_KEY:-}
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    depends_on:
      - postgres
      - redis
    networks:
      - bizosaas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8029/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    container_name: bizosaas-marketing-postgres
    environment:
      - POSTGRES_DB=bizosaas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
    networks:
      - bizosaas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: bizosaas-marketing-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - bizosaas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  bizosaas-network:
    driver: bridge