apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mautic-pvc
  namespace: bizosaas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mautic-uploads-pvc
  namespace: bizosaas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mautic-config
  namespace: bizosaas
data:
  MAUTIC_DB_HOST: "postgres-service"
  MAUTIC_DB_PORT: "5432"
  MAUTIC_DB_NAME: "mautic"
  MAUTIC_DB_USER: "mautic_user"
  MAUTIC_TRUSTED_PROXIES: "0.0.0.0/0"
  MAUTIC_RUN_CRON_JOBS: "true"
  MAUTIC_CRON_HUBSPOT: "1"
  MAUTIC_CRON_SALESFORCE: "1"
  MAUTIC_CRON_PIPEDRIVE: "1"
  MAUTIC_INSTALL_FORCE: "0"
  MAUTIC_ENV: "prod"

---
apiVersion: v1
kind: Secret
metadata:
  name: mautic-secrets
  namespace: bizosaas
type: Opaque
stringData:
  mautic-db-password: "MauticSecure2024!"
  mautic-admin-password: "MauticAdmin2024!"
  mautic-secret-key: "mautic-secret-key-change-me-in-production"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mautic
  namespace: bizosaas
  labels:
    app: mautic
    component: sales-funnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mautic
  template:
    metadata:
      labels:
        app: mautic
    spec:
      securityContext:
        fsGroup: 33  # www-data group ID
      containers:
      - name: mautic
        image: mautic/mautic:v5-apache
        ports:
        - containerPort: 80
        env:
        - name: MAUTIC_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mautic-config
              key: MAUTIC_DB_HOST
        - name: MAUTIC_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: mautic-config
              key: MAUTIC_DB_PORT
        - name: MAUTIC_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mautic-config
              key: MAUTIC_DB_NAME
        - name: MAUTIC_DB_USER
          valueFrom:
            configMapKeyRef:
              name: mautic-config
              key: MAUTIC_DB_USER
        - name: MAUTIC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mautic-secrets
              key: mautic-db-password
        - name: MAUTIC_TRUSTED_PROXIES
          valueFrom:
            configMapKeyRef:
              name: mautic-config
              key: MAUTIC_TRUSTED_PROXIES
        - name: MAUTIC_RUN_CRON_JOBS
          valueFrom:
            configMapKeyRef:
              name: mautic-config
              key: MAUTIC_RUN_CRON_JOBS
        - name: MAUTIC_CRON_HUBSPOT
          valueFrom:
            configMapKeyRef:
              name: mautic-config
              key: MAUTIC_CRON_HUBSPOT
        - name: MAUTIC_CRON_SALESFORCE
          valueFrom:
            configMapKeyRef:
              name: mautic-config
              key: MAUTIC_CRON_SALESFORCE
        - name: MAUTIC_CRON_PIPEDRIVE
          valueFrom:
            configMapKeyRef:
              name: mautic-config
              key: MAUTIC_CRON_PIPEDRIVE
        - name: MAUTIC_INSTALL_FORCE
          valueFrom:
            configMapKeyRef:
              name: mautic-config
              key: MAUTIC_INSTALL_FORCE
        - name: MAUTIC_ENV
          valueFrom:
            configMapKeyRef:
              name: mautic-config
              key: MAUTIC_ENV
        - name: MAUTIC_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mautic-secrets
              key: mautic-secret-key
        - name: MAUTIC_ADMIN_USERNAME
          value: "admin"
        - name: MAUTIC_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mautic-secrets
              key: mautic-admin-password
        - name: MAUTIC_ADMIN_EMAIL
          value: "admin@bizoholic.com"
        - name: MAUTIC_ADMIN_FIRSTNAME
          value: "BizoholicSaaS"
        - name: MAUTIC_ADMIN_LASTNAME
          value: "Administrator"
        volumeMounts:
        - name: mautic-storage
          mountPath: /var/www/html/app/cache
          subPath: cache
        - name: mautic-storage
          mountPath: /var/www/html/app/logs
          subPath: logs
        - name: mautic-storage
          mountPath: /var/www/html/app/spool
          subPath: spool
        - name: mautic-uploads
          mountPath: /var/www/html/media
        - name: mautic-uploads
          mountPath: /var/www/html/themes
          subPath: themes
        - name: mautic-uploads
          mountPath: /var/www/html/plugins
          subPath: plugins
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/contacts
            port: 80
            httpHeaders:
            - name: Authorization
              value: "Basic YWRtaW46TWF1dGljQWRtaW4yMDI0IQ=="
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/contacts
            port: 80
            httpHeaders:
            - name: Authorization
              value: "Basic YWRtaW46TWF1dGljQWRtaW4yMDI0IQ=="
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 18  # Allow up to 3 minutes for startup
      volumes:
      - name: mautic-storage
        persistentVolumeClaim:
          claimName: mautic-pvc
      - name: mautic-uploads
        persistentVolumeClaim:
          claimName: mautic-uploads-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mautic-service
  namespace: bizosaas
  labels:
    app: mautic
spec:
  selector:
    app: mautic
  ports:
  - name: http
    port: 8090
    targetPort: 80
    protocol: TCP
  type: ClusterIP

---
# Mautic Cron Job for periodic tasks
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mautic-cron-segments
  namespace: bizosaas
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mautic-cron-segments
            image: mautic/mautic:v5-apache
            command:
            - /bin/bash
            - -c
            - |
              cd /var/www/html
              php bin/console mautic:segments:update --env=prod --no-interaction
            env:
            - name: MAUTIC_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mautic-config
                  key: MAUTIC_DB_HOST
            - name: MAUTIC_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mautic-config
                  key: MAUTIC_DB_PORT
            - name: MAUTIC_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mautic-config
                  key: MAUTIC_DB_NAME
            - name: MAUTIC_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mautic-config
                  key: MAUTIC_DB_USER
            - name: MAUTIC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mautic-secrets
                  key: mautic-db-password
          restartPolicy: OnFailure
      successfulJobsHistoryLimit: 3
      failedJobsHistoryLimit: 3

---
# Mautic Cron Job for campaign triggers
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mautic-cron-campaigns
  namespace: bizosaas
spec:
  schedule: "*/10 * * * *"  # Every 10 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mautic-cron-campaigns
            image: mautic/mautic:v5-apache
            command:
            - /bin/bash
            - -c
            - |
              cd /var/www/html
              php bin/console mautic:campaigns:trigger --env=prod --no-interaction
            env:
            - name: MAUTIC_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mautic-config
                  key: MAUTIC_DB_HOST
            - name: MAUTIC_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mautic-config
                  key: MAUTIC_DB_PORT
            - name: MAUTIC_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mautic-config
                  key: MAUTIC_DB_NAME
            - name: MAUTIC_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mautic-config
                  key: MAUTIC_DB_USER
            - name: MAUTIC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mautic-secrets
                  key: mautic-db-password
          restartPolicy: OnFailure
      successfulJobsHistoryLimit: 3
      failedJobsHistoryLimit: 3

---
# Mautic Cron Job for email queue processing
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mautic-cron-emails
  namespace: bizosaas
spec:
  schedule: "*/2 * * * *"  # Every 2 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mautic-cron-emails
            image: mautic/mautic:v5-apache
            command:
            - /bin/bash
            - -c
            - |
              cd /var/www/html
              php bin/console mautic:emails:send --env=prod --no-interaction --time-limit=60
            env:
            - name: MAUTIC_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mautic-config
                  key: MAUTIC_DB_HOST
            - name: MAUTIC_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mautic-config
                  key: MAUTIC_DB_PORT
            - name: MAUTIC_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mautic-config
                  key: MAUTIC_DB_NAME
            - name: MAUTIC_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mautic-config
                  key: MAUTIC_DB_USER
            - name: MAUTIC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mautic-secrets
                  key: mautic-db-password
          restartPolicy: OnFailure
      successfulJobsHistoryLimit: 3
      failedJobsHistoryLimit: 3