# BizOSaaS Frontend Services - Next.js frontend applications
# Dokploy Project: bizosaas-frontend
# Dependencies: Requires bizosaas-platform and bizosaas-storage to be running first

services:
  # ========================================================================================
  # BIZOHOLIC FRONTEND - Main marketing platform
  # ========================================================================================
  bizoholic-frontend:
    image: bizosaas/bizoholic-frontend:latest
    container_name: bizoholic-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.bizoholic.com
      - NEXT_PUBLIC_CMS_URL=https://cms.bizoholic.com
      - NEXT_PUBLIC_ADMIN_URL=https://admin.bizoholic.com
      - NEXT_PUBLIC_DIRECTORY_URL=https://directory.bizoholic.com
      - NEXT_PUBLIC_TELEGRAM_URL=https://bots.bizoholic.com
      - NEXT_PUBLIC_IMAGES_URL=https://images.bizoholic.com
      - NEXT_PUBLIC_SITE_NAME=Bizoholic
      - NEXT_PUBLIC_SITE_DESCRIPTION=AI-Powered Marketing Agency Platform
      - NEXT_PUBLIC_DOMAIN=bizoholic.com
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bizoholic-frontend.rule=Host(`bizoholic.com`)"
      - "traefik.http.services.bizoholic-frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.bizoholic-frontend.tls=true"
      - "traefik.http.routers.bizoholic-frontend.tls.certresolver=letsencrypt"

  # ========================================================================================
  # CORELDOVE FRONTEND - E-commerce platform
  # ========================================================================================
  coreldove-frontend:
    image: bizosaas/coreldove-frontend:latest
    container_name: coreldove-frontend
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_PLATFORM_MODE=coreldove
      - NEXT_PUBLIC_API_URL=https://api.bizoholic.com
      - NEXT_PUBLIC_SALEOR_API_URL=https://api.coreldove.com/graphql/
      - NEXT_PUBLIC_CMS_URL=https://cms.bizoholic.com
      - NEXT_PUBLIC_STOREFRONT_URL=https://store.coreldove.com
      - NEXT_PUBLIC_SITE_NAME=CoreLDove
      - NEXT_PUBLIC_SITE_DESCRIPTION=AI-Powered E-commerce Platform
      - NEXT_PUBLIC_DOMAIN=coreldove.com
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coreldove-frontend.rule=Host(`coreldove.com`)"
      - "traefik.http.services.coreldove-frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.coreldove-frontend.tls=true"
      - "traefik.http.routers.coreldove-frontend.tls.certresolver=letsencrypt"

  # ========================================================================================
  # CLIENT DASHBOARD - Multi-tenant client interface
  # ========================================================================================
  client-dashboard:
    image: bizosaas/client-dashboard:latest
    container_name: client-dashboard
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_PLATFORM_MODE=multi_tenant
      - NEXT_PUBLIC_API_URL=https://api.bizoholic.com
      - NEXT_PUBLIC_ADMIN_URL=https://admin.bizoholic.com
      - NEXT_PUBLIC_CMS_URL=https://cms.bizoholic.com
      - NEXT_PUBLIC_DIRECTORY_URL=https://directory.bizoholic.com
      - NEXT_PUBLIC_SITE_NAME=Client Dashboard
      - NEXT_PUBLIC_SITE_DESCRIPTION=BizOSaaS Client Management Portal
      - NEXT_PUBLIC_DOMAIN=dashboard.bizoholic.com
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client-dashboard.rule=Host(`dashboard.bizoholic.com`)"
      - "traefik.http.services.client-dashboard.loadbalancer.server.port=3000"
      - "traefik.http.routers.client-dashboard.tls=true"
      - "traefik.http.routers.client-dashboard.tls.certresolver=letsencrypt"

# ========================================================================================
# NETWORKS (External - created by Dokploy)
# ========================================================================================
networks:
  dokploy-network:
    external: true