#!/bin/bash
# Domain Configuration Script for BizOSaaS Staging

API_KEY="agent_supportUMExjyxtGrPXnqZoTkKEeBAhAdHnTWpNqyUbFfbVPSYgIiGCNCCcsZpGnMaRvCbi"
DOKPLOY_URL="https://dk.bizoholic.com"
FRONTEND_COMPOSE_ID="zz6VpI3h8BFXPUTZZb01G"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "=========================================="
echo "BizOSaaS Domain Configuration Guide"
echo "=========================================="
echo ""

echo -e "${YELLOW}Domain Configuration Strategy:${NC}"
echo ""
echo "We'll use SEPARATE SUBDOMAINS for each service:"
echo ""
echo "1. stg.bizoholic.com → Port 3000 (Client Portal)"
echo "   Primary entry point for client login"
echo ""
echo "2. stg.marketing.bizoholic.com → Port 3001 (Bizoholic Marketing)"
echo "   Digital marketing agency website"
echo ""
echo "3. stg.admin.bizoholic.com → Port 3005 (Admin Dashboard)"
echo "   Platform administration interface"
echo ""
echo "4. stg.coreldove.com → Port 3002 (CorelDove E-commerce)"
echo "   E-commerce storefront"
echo ""
echo "5. stg.directory.bizoholic.com → Port 3003 (Business Directory)"
echo "   Business listings and directory"
echo ""
echo "6. stg.thrillring.com → Port 3004 (ThrillRing Gaming)"
echo "   Gaming platform"
echo ""
echo "=========================================="
echo ""

echo -e "${GREEN}Step 1: DNS Configuration${NC}"
echo ""
echo "Add these DNS A records in your domain registrar:"
echo ""
echo "Domain                         Type  Value"
echo "-----------------------------------------------------------"
echo "stg.bizoholic.com              A     194.238.16.237"
echo "stg.marketing.bizoholic.com    A     194.238.16.237"
echo "stg.admin.bizoholic.com        A     194.238.16.237"
echo "stg.directory.bizoholic.com    A     194.238.16.237"
echo "stg.coreldove.com              A     194.238.16.237"
echo "stg.thrillring.com             A     194.238.16.237"
echo ""
echo "⏳ DNS propagation can take 5-60 minutes"
echo ""

read -p "Press Enter once DNS records are added..."

echo ""
echo -e "${GREEN}Step 2: Configure Domains in Dokploy${NC}"
echo ""
echo "For each service, you'll need to:"
echo "1. Open: $DOKPLOY_URL"
echo "2. Navigate to: Projects → Frontend Services → [Service Name]"
echo "3. Click: Domains tab"
echo "4. Add domain with SSL enabled"
echo ""

echo "Would you like to see the detailed Dokploy UI steps?"
read -p "(y/n): " show_details

if [ "$show_details" = "y" ]; then
    echo ""
    echo "=========================================="
    echo "Detailed Dokploy Configuration Steps"
    echo "=========================================="
    echo ""

    echo "SERVICE 1: Client Portal (Port 3000)"
    echo "-------------------------------------------"
    echo "1. Go to: Frontend Services → client-portal"
    echo "2. Click: Domains tab"
    echo "3. Click: Add Domain"
    echo "4. Enter: stg.bizoholic.com"
    echo "5. Port: 3000"
    echo "6. Enable: HTTPS (Let's Encrypt)"
    echo "7. Click: Save"
    echo ""

    echo "SERVICE 2: Bizoholic Marketing (Port 3001)"
    echo "-------------------------------------------"
    echo "1. Go to: Frontend Services → bizoholic-frontend"
    echo "2. Click: Domains tab"
    echo "3. Click: Add Domain"
    echo "4. Enter: stg.marketing.bizoholic.com"
    echo "5. Port: 3001"
    echo "6. Enable: HTTPS (Let's Encrypt)"
    echo "7. Click: Save"
    echo ""

    echo "SERVICE 3: CorelDove E-commerce (Port 3002)"
    echo "-------------------------------------------"
    echo "1. Go to: Frontend Services → coreldove-frontend"
    echo "2. Click: Domains tab"
    echo "3. Click: Add Domain"
    echo "4. Enter: stg.coreldove.com"
    echo "5. Port: 3002"
    echo "6. Enable: HTTPS (Let's Encrypt)"
    echo "7. Click: Save"
    echo ""

    echo "SERVICE 4: Business Directory (Port 3003)"
    echo "-------------------------------------------"
    echo "1. Go to: Frontend Services → business-directory-frontend"
    echo "2. Click: Domains tab"
    echo "3. Click: Add Domain"
    echo "4. Enter: stg.directory.bizoholic.com"
    echo "5. Port: 3003"
    echo "6. Enable: HTTPS (Let's Encrypt)"
    echo "7. Click: Save"
    echo ""

    echo "SERVICE 5: ThrillRing Gaming (Port 3004)"
    echo "-------------------------------------------"
    echo "1. Go to: Frontend Services → thrillring-gaming"
    echo "2. Click: Domains tab"
    echo "3. Click: Add Domain"
    echo "4. Enter: stg.thrillring.com"
    echo "5. Port: 3004"
    echo "6. Enable: HTTPS (Let's Encrypt)"
    echo "7. Click: Save"
    echo ""

    echo "SERVICE 6: Admin Dashboard (Port 3005)"
    echo "-------------------------------------------"
    echo "1. Go to: Frontend Services → admin-dashboard"
    echo "2. Click: Domains tab"
    echo "3. Click: Add Domain"
    echo "4. Enter: stg.admin.bizoholic.com"
    echo "5. Port: 3005"
    echo "6. Enable: HTTPS (Let's Encrypt)"
    echo "7. Click: Save"
    echo ""
fi

echo ""
echo "=========================================="
echo -e "${GREEN}Step 3: Verify SSL Certificates${NC}"
echo "=========================================="
echo ""
echo "After configuring all domains, verify SSL:"
echo ""
echo "1. Wait 2-5 minutes for Let's Encrypt to generate certificates"
echo "2. Visit each domain in your browser:"
echo "   - https://stg.bizoholic.com"
echo "   - https://stg.marketing.bizoholic.com"
echo "   - https://stg.admin.bizoholic.com"
echo "   - https://stg.coreldove.com"
echo "   - https://stg.directory.bizoholic.com"
echo "   - https://stg.thrillring.com"
echo ""
echo "3. Verify the lock icon appears (SSL working)"
echo ""

echo "=========================================="
echo -e "${GREEN}Configuration Complete!${NC}"
echo "=========================================="
echo ""
echo "Your BizOSaaS platform is now accessible at:"
echo ""
echo "✓ Client Portal: https://stg.bizoholic.com"
echo "✓ Marketing Site: https://stg.marketing.bizoholic.com"
echo "✓ Admin Dashboard: https://stg.admin.bizoholic.com"
echo "✓ CorelDove Store: https://stg.coreldove.com"
echo "✓ Business Directory: https://stg.directory.bizoholic.com"
echo "✓ ThrillRing Gaming: https://stg.thrillring.com"
echo ""
