#!/bin/bash

# BizOSaaS Platform - STAGING Environment Deployment Script
# Deploys all 20 containers with staging subdomains for testing

set -e

VPS_IP="194.238.16.237"
DOKPLOY_URL="http://${VPS_IP}:3000"
ENVIRONMENT="staging"

echo "🧪 BizOSaaS Platform - STAGING Environment Deployment"
echo "====================================================="
echo "Environment: $ENVIRONMENT"
echo "Target VPS: $VPS_IP"
echo "Dokploy URL: $DOKPLOY_URL"
echo "Total Containers: 20"
echo "Staging Domains: stg.bizoholic.com, stg.coreldove.com, stg.thrillring.com"
echo "Timestamp: $(date)"
echo ""

# Function to show staging domain strategy
show_staging_domains() {
    echo "🧪 STAGING DOMAIN STRATEGY:"
    echo "=========================="
    echo ""
    echo "Primary Staging Subdomains (3):"
    echo "  • stg.bizoholic.com    → Bizoholic Marketing (Testing)"
    echo "  • stg.coreldove.com    → CorelDove E-commerce (Testing)"
    echo "  • stg.thrillring.com   → ThrillRing Gaming (Testing)"
    echo ""
    echo "Staging Path-Based Routes:"
    echo "  • stg.bizoholic.com/login/  → Client Portal (Testing)"
    echo "  • stg.bizoholic.com/admin/  → Admin Dashboard (Testing)"
    echo ""
    echo "Backend Services (Internal Only):"
    echo "  • All 14 backend + infrastructure services"
    echo "  • No external domains needed"
    echo "  • Accessible via AI Central Hub routing"
    echo ""
}

# Function to show staging benefits
show_staging_benefits() {
    echo "✅ STAGING ENVIRONMENT BENEFITS:"
    echo "==============================="
    echo ""
    echo "Testing Advantages:"
    echo "  • Safe testing environment before production"
    echo "  • Real SSL certificates for HTTPS testing"
    echo "  • Complete 20-container platform functionality"
    echo "  • Performance and load testing capabilities"
    echo "  • Security testing and vulnerability assessment"
    echo ""
    echo "Development Features:"
    echo "  • DEBUG_MODE=true for detailed logging"
    echo "  • ENABLE_ANALYTICS=false to avoid test data"
    echo "  • NODE_ENV=staging for environment-specific behavior"
    echo "  • Enhanced error reporting and debugging"
    echo ""
    echo "Cost Efficiency:"
    echo "  • Uses existing VPS infrastructure"
    echo "  • Free staging subdomains"
    echo "  • Free SSL certificates (Let's Encrypt)"
    echo "  • Zero additional hosting costs"
    echo ""
}

# Function to show container breakdown
show_container_breakdown() {
    echo "📊 STAGING CONTAINER BREAKDOWN (20 Total):"
    echo "=========================================="
    echo ""
    echo "Infrastructure Services (6 containers - Internal):"
    echo "  1. PostgreSQL Database (5432) - Multi-tenant staging data"
    echo "  2. Redis Cache (6379) - Session and cache storage"
    echo "  3. HashiCorp Vault (8200) - Secrets management"
    echo "  4. Temporal Server (7233) - Workflow engine"
    echo "  5. Temporal UI (8082) - Workflow management interface"
    echo "  6. Temporal Integration (8009) - Custom workflow integration"
    echo ""
    echo "Backend Services (8 containers - Internal):"
    echo "  1. AI Central Hub (8001) - Main API coordinator and router"
    echo "  2. Django CRM (8003) - Customer relationship management"
    echo "  3. Business Directory API (8004) - Directory service backend"
    echo "  4. CorelDove E-commerce API (8005) - E-commerce backend"
    echo "  5. AI Agents Service (8010) - Multi-model AI coordination"
    echo "  6. Amazon Sourcing API (8085) - Product sourcing integration"
    echo "  7. Saleor E-commerce Engine (8000) - Advanced e-commerce platform"
    echo "  8. Wagtail CMS (8002) - Headless content management"
    echo ""
    echo "Frontend Applications (6 containers - Staging Domains):"
    echo "  1. Bizoholic Marketing (3000) → stg.bizoholic.com"
    echo "  2. Client Portal (3001) → stg.bizoholic.com/login/"
    echo "  3. CorelDove E-commerce (3002) → stg.coreldove.com"
    echo "  4. Business Directory (3004) → Internal testing"
    echo "  5. ThrillRing Gaming (3005) → stg.thrillring.com"
    echo "  6. Admin Dashboard (3009) → stg.bizoholic.com/admin/"
    echo ""
}

# Function to show DNS configuration
show_dns_configuration() {
    echo "🌍 STAGING DNS CONFIGURATION:"
    echo "============================"
    echo ""
    echo "Required DNS Records (Point to $VPS_IP):"
    echo ""
    echo "# Add these subdomains to your DNS provider"
    echo "stg.bizoholic.com     A    $VPS_IP"
    echo "stg.coreldove.com     A    $VPS_IP"
    echo "stg.thrillring.com    A    $VPS_IP"
    echo ""
    echo "DNS Verification Commands:"
    echo "  dig stg.bizoholic.com"
    echo "  dig stg.coreldove.com"
    echo "  dig stg.thrillring.com"
    echo ""
    echo "Expected Response:"
    echo "  ;; ANSWER SECTION:"
    echo "  stg.bizoholic.com.    300    IN    A    $VPS_IP"
    echo ""
}

# Function to show deployment steps
show_deployment_steps() {
    echo "📋 STAGING DEPLOYMENT STEPS:"
    echo "============================"
    echo ""
    echo "Step 1: Configure Staging DNS"
    echo "  • Add staging subdomains to your DNS provider"
    echo "  • Wait for DNS propagation (5-30 minutes)"
    echo "  • Verify DNS resolution before proceeding"
    echo ""
    echo "Step 2: Access Dokploy Dashboard"
    echo "  • URL: $DOKPLOY_URL"
    echo "  • Login with your administrator credentials"
    echo ""
    echo "Step 3: Create Staging Projects"
    echo "  • Project 1: 'bizosaas-infrastructure-staging'"
    echo "  • Project 2: 'bizosaas-backend-staging'"
    echo "  • Project 3: 'bizosaas-frontend-staging'"
    echo ""
    echo "Step 4: Deploy Infrastructure (No External Domains)"
    echo "  • Upload: dokploy-infrastructure.yml"
    echo "  • Deploy: 6 infrastructure containers"
    echo "  • Verify: Database and cache services running"
    echo ""
    echo "Step 5: Deploy Backend Services (No External Domains)"
    echo "  • Upload: dokploy-backend.yml"
    echo "  • Deploy: 8 backend API containers"
    echo "  • Verify: AI Central Hub (8001) accessible internally"
    echo ""
    echo "Step 6: Deploy Frontend with Staging Domains"
    echo "  • Upload: dokploy-frontend-staging.yml"
    echo "  • Configure staging subdomains:"
    echo ""
    echo "    Bizoholic Staging:"
    echo "      Domain: stg.bizoholic.com"
    echo "      SSL: Enable Let's Encrypt"
    echo "      Container Port: 3000"
    echo ""
    echo "    CorelDove Staging:"
    echo "      Domain: stg.coreldove.com"
    echo "      SSL: Enable Let's Encrypt"
    echo "      Container Port: 3002"
    echo ""
    echo "    ThrillRing Staging:"
    echo "      Domain: stg.thrillring.com"
    echo "      SSL: Enable Let's Encrypt"
    echo "      Container Port: 3005"
    echo ""
    echo "    Client Portal Staging:"
    echo "      Host: stg.bizoholic.com"
    echo "      Path: /login/"
    echo "      Container Port: 3001"
    echo "      Strip Path: Yes"
    echo ""
    echo "    Admin Dashboard Staging:"
    echo "      Host: stg.bizoholic.com"
    echo "      Path: /admin/"
    echo "      Container Port: 3009"
    echo "      Strip Path: Yes"
    echo ""
}

# Function to show testing procedures
show_testing_procedures() {
    echo "🧪 STAGING TESTING PROCEDURES:"
    echo "============================="
    echo ""
    echo "Functional Testing Checklist:"
    echo "  □ Marketing website: https://stg.bizoholic.com"
    echo "  □ E-commerce store: https://stg.coreldove.com"
    echo "  □ Gaming platform: https://stg.thrillring.com"
    echo "  □ Client portal: https://stg.bizoholic.com/login/"
    echo "  □ Admin dashboard: https://stg.bizoholic.com/admin/"
    echo ""
    echo "Technical Verification:"
    echo "  □ All 20 containers running and healthy"
    echo "  □ SSL certificates active on all staging domains"
    echo "  □ API routing through AI Central Hub functioning"
    echo "  □ Database connectivity and CRUD operations"
    echo "  □ Authentication and authorization flows"
    echo ""
    echo "Performance Testing:"
    echo "  □ Page load times < 3 seconds"
    echo "  □ API response times < 500ms"
    echo "  □ Database query performance acceptable"
    echo "  □ Image and asset optimization verified"
    echo "  □ Mobile responsiveness on all devices"
    echo ""
    echo "Security Testing:"
    echo "  □ HTTPS enforced on all staging domains"
    echo "  □ Path traversal and injection protection"
    echo "  □ Authentication security measures"
    echo "  □ API rate limiting and validation"
    echo "  □ Cross-site scripting (XSS) prevention"
    echo ""
}

# Function to show staging to production migration
show_production_migration() {
    echo "🚀 STAGING TO PRODUCTION MIGRATION:"
    echo "=================================="
    echo ""
    echo "Pre-Production Checklist:"
    echo "  □ All staging tests passed successfully"
    echo "  □ Performance benchmarks met"
    echo "  □ Security audit completed"
    echo "  □ Load testing results acceptable"
    echo "  □ User acceptance testing approved"
    echo ""
    echo "Production Migration Process:"
    echo "  1. Backup current production (if any)"
    echo "  2. Update DNS for production domains:"
    echo "     • bizoholic.com → $VPS_IP"
    echo "     • coreldove.com → $VPS_IP"
    echo "     • thrillring.com → $VPS_IP"
    echo "  3. Deploy production configuration"
    echo "  4. Switch environment variables from staging to production"
    echo "  5. Enable production analytics and monitoring"
    echo "  6. Verify production functionality"
    echo "  7. Monitor for 24-48 hours"
    echo ""
    echo "Domain Migration Mapping:"
    echo "  stg.bizoholic.com → bizoholic.com"
    echo "  stg.coreldove.com → coreldove.com"
    echo "  stg.thrillring.com → thrillring.com"
    echo "  stg.bizoholic.com/login/ → bizoholic.com/login/"
    echo "  stg.bizoholic.com/admin/ → bizoholic.com/admin/"
    echo ""
}

# Function to show files included
show_files_included() {
    echo "📁 STAGING DEPLOYMENT FILES:"
    echo "==========================="
    echo ""
    echo "Docker Compose Configurations:"
    echo "  • dokploy-infrastructure.yml (6 infrastructure containers)"
    echo "  • dokploy-backend.yml (8 backend service containers)"
    echo "  • dokploy-frontend-staging.yml (6 frontend staging containers)"
    echo ""
    echo "Deployment Scripts:"
    echo "  • deploy-staging-to-dokploy.sh (this comprehensive guide)"
    echo "  • health-check-staging.sh (staging environment verification)"
    echo ""
    echo "Configuration Files:"
    echo "  • .env.staging (staging environment variables)"
    echo "  • staging-test-suite.sh (automated testing script)"
    echo ""
    echo "Documentation:"
    echo "  • STAGING_DOMAIN_STRATEGY.md (complete staging strategy)"
    echo "  • DEPLOYMENT_ANALYSIS_REPORT.md (deployment analysis)"
    echo "  • CORRECTED_DOMAIN_STRATEGY.md (original domain corrections)"
    echo ""
}

# Main execution function
main() {
    show_staging_domains
    show_staging_benefits
    show_container_breakdown
    show_dns_configuration
    show_deployment_steps
    show_testing_procedures
    show_production_migration
    show_files_included

    echo "🎯 STAGING DEPLOYMENT SUMMARY:"
    echo "============================="
    echo ""
    echo "✅ Environment: STAGING (Safe Testing)"
    echo "✅ Container Count: 20/20 confirmed and ready"
    echo "✅ Staging Domains: stg.bizoholic.com, stg.coreldove.com, stg.thrillring.com"
    echo "✅ Path Routing: /login/ and /admin/ configured"
    echo "✅ SSL Strategy: Automatic Let's Encrypt for realistic testing"
    echo "✅ Testing Framework: Comprehensive validation procedures"
    echo "✅ Migration Plan: Clear path to production deployment"
    echo ""
    echo "🧪 Ready for staging deployment and comprehensive testing!"
    echo ""
    echo "Next Steps:"
    echo "1. Configure staging DNS for the 3 subdomains"
    echo "2. Access Dokploy at $DOKPLOY_URL"
    echo "3. Follow the deployment steps above"
    echo "4. Execute comprehensive testing procedures"
    echo "5. Plan production migration based on staging results"
    echo ""
    echo "Expected Staging Result:"
    echo "• All 20 containers operational in staging environment"
    echo "• 3 staging subdomains with SSL certificates"
    echo "• Path-based routing for portal/admin testing"
    echo "• Complete BizOSaaS platform ready for validation"
    echo "• Clear migration path to production"
    echo ""
    echo "Cost: $0 (uses existing infrastructure + free subdomains)"
    echo "Timeline: 1-2 weeks of thorough testing before production"
    echo ""
}

# Execute main function
main "$@"