version: '3.8'

services:
  vault-integration:
    build: .
    container_name: bizosaas-vault-integration
    ports:
      - "8201:8201"
    environment:
      - VAULT_URL=http://bizosaas-vault:8200
      - VAULT_TOKEN=root
    depends_on:
      - vault
    networks:
      - bizosaas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8201/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  vault:
    image: hashicorp/vault:1.18.1
    container_name: bizosaas-vault
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    command: vault server -dev -dev-listen-address=0.0.0.0:8200
    networks:
      - bizosaas-network
    restart: unless-stopped
    volumes:
      - vault-data:/vault/data
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  bizosaas-network:
    external: true

volumes:
  vault-data: