version: '3.8'

# BizOSaaS Platform - Integration with Existing Services
# Works with currently running containers and fixes port allocation

services:
  # ===========================================
  # FRONTEND SERVICES - CORRECT PORT ALLOCATION
  # ===========================================

  # Port 3000: BizOSaaS Admin Dashboard (TailAdmin v2) - PRD SPECIFICATION
  bizosaas-admin:
    image: bizosaas/tailadmin-v2-unified:latest
    container_name: bizosaas-admin-3000
    ports:
      - "3000:8080"  # Map to internal port 8080
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BRAIN_API_URL=http://localhost:8001
      - NEXT_PUBLIC_AUTH_API_URL=http://localhost:8007
      - NEXT_PUBLIC_WAGTAIL_URL=http://localhost:8006
      - NEXT_PUBLIC_SUPERSET_URL=http://localhost:8088
      - NEXT_PUBLIC_WEBSOCKET_URL=ws://localhost:8001/ws/realtime
      - NEXT_PUBLIC_PLATFORM=bizosaas-admin
      - PORT=8080
    restart: unless-stopped
    network_mode: bridge
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Port 3001: Bizoholic Marketing Frontend - PRD SPECIFICATION
  bizoholic-marketing:
    image: bizoholic-bizoholic-frontend:latest
    container_name: bizoholic-marketing-3001
    ports:
      - "3001:3000"  # Map to internal port 3000
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BRAIN_API_URL=http://localhost:8001
      - NEXT_PUBLIC_AUTH_API_URL=http://localhost:8007
      - NEXT_PUBLIC_WAGTAIL_URL=http://localhost:8006
      - NEXT_PUBLIC_PLATFORM=bizoholic-marketing
      - WAGTAIL_API_BASE_URL=http://localhost:8006/api
      - PORT=3000
    restart: unless-stopped
    network_mode: bridge

  # Port 3002: CoreLDove E-commerce Frontend - PRD SPECIFICATION (Keep existing)
  coreldove-ecommerce:
    image: bizoholic-coreldove-frontend:latest
    container_name: coreldove-ecommerce-3002
    ports:
      - "3002:3000"  # Keep existing mapping
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BRAIN_API_URL=http://localhost:8001
      - NEXT_PUBLIC_AUTH_API_URL=http://localhost:8007
      - NEXT_PUBLIC_SALEOR_URL=http://localhost:8010
      - NEXT_PUBLIC_SALEOR_API_URL=http://localhost:8010/graphql/
      - NEXT_PUBLIC_PLATFORM=coreldove-ecommerce
      - PORT=3000
    restart: unless-stopped
    network_mode: bridge

  # ===========================================
  # MISSING BACKEND SERVICES
  # ===========================================

  # FastAPI Brain Gateway (Port 8001) - MISSING FROM CURRENT SETUP
  bizosaas-brain:
    build:
      context: ./ai/services/bizosaas-brain
      dockerfile: Dockerfile
    container_name: bizosaas-brain-8001
    ports:
      - "8001:8001"
    environment:
      # Use existing PostgreSQL
      - DATABASE_URL=postgresql://admin:securepassword@localhost:5432/bizosaas
      # Use existing Redis
      - REDIS_URL=redis://localhost:6379/0
      # API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy-key}
      - JWT_SECRET=${JWT_SECRET:-dev-secret-key}
      - ENVIRONMENT=development
      # Connect to existing services
      - WAGTAIL_URL=http://localhost:8006
      - VAULT_URL=http://localhost:8200
    volumes:
      - ./ai/services/bizosaas-brain:/app
    restart: unless-stopped
    network_mode: bridge

  # Auth Service v2 (Port 8007) - MISSING FROM CURRENT SETUP  
  bizosaas-auth-v2:
    build:
      context: ./core/services/auth-service-v2
      dockerfile: Dockerfile
    container_name: bizosaas-auth-v2-8007
    ports:
      - "8007:8007"
    environment:
      # Use existing PostgreSQL
      - DATABASE_URL=postgresql://admin:securepassword@localhost:5432/bizosaas
      # Use existing Redis for sessions
      - REDIS_URL=redis://localhost:6379/1
      - JWT_SECRET=${JWT_SECRET:-dev-secret-key}
      - SECRET_KEY=auth-service-secret-key-development
    restart: unless-stopped
    network_mode: bridge

  # Saleor Backend (Port 8010) - Connect to existing Saleor DB
  saleor-backend:
    image: ghcr.io/saleor/saleor:latest
    container_name: saleor-backend-8010
    ports:
      - "8010:8000"
    environment:
      # Use existing Saleor PostgreSQL
      - DATABASE_URL=postgresql://saleor:saleor@localhost:5433/saleor
      # Use existing Saleor Redis
      - REDIS_URL=redis://localhost:6380/0
      - SECRET_KEY=saleor-secret-key-development
      - DEBUG=true
      - ALLOWED_HOSTS=localhost,127.0.0.1,saleor-backend
      - DEFAULT_FROM_EMAIL=noreply@bizosaas.local
    restart: unless-stopped
    network_mode: bridge

# ===========================================
# VOLUMES
# ===========================================
volumes:
  superset_data:
    name: bizosaas-superset-data