version: '3.8'

# CoreLDove E-commerce Stack - E-commerce Frontend and Services
# Dokploy Project: coreldove (or can be part of bizosaas)
# Services: E-commerce Storefront, Saleor Backend

services:
  # ===========================================
  # CORELDOVE E-COMMERCE FRONTEND - PORT 3002
  # ===========================================
  
  coreldove-ecommerce:
    image: bizoholic-coreldove-frontend:latest
    container_name: coreldove-ecommerce-3002
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BRAIN_API_URL=http://host.docker.internal:8001
      - NEXT_PUBLIC_AUTH_API_URL=http://host.docker.internal:8007
      - NEXT_PUBLIC_SALEOR_URL=http://saleor-backend:8000
      - NEXT_PUBLIC_SALEOR_API_URL=http://saleor-backend:8000/graphql/
      - NEXT_PUBLIC_PLATFORM=coreldove-ecommerce
      - PORT=3000
    restart: unless-stopped
    networks:
      - coreldove-network
    depends_on:
      - saleor-backend
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coreldove-ecommerce.rule=Host(`coreldove.bizosaas.local`) || Host(`localhost:3002`)"
      - "traefik.http.services.coreldove-ecommerce.loadbalancer.server.port=3000"

  # ===========================================
  # SALEOR E-COMMERCE BACKEND - PORT 8010
  # ===========================================
  
  saleor-backend:
    image: ghcr.io/saleor/saleor:latest
    container_name: saleor-backend-8010
    ports:
      - "8010:8000"
    environment:
      # Use existing Saleor PostgreSQL
      - DATABASE_URL=postgresql://saleor:saleor@host.docker.internal:5433/saleor
      # Use existing Saleor Redis
      - REDIS_URL=redis://host.docker.internal:6380/0
      - SECRET_KEY=saleor-secret-key-production
      - DEBUG=false
      - ALLOWED_HOSTS=localhost,127.0.0.1,saleor-backend,coreldove.bizosaas.local
      - DEFAULT_FROM_EMAIL=noreply@coreldove.bizosaas.local
      - ENABLE_SSL_REDIRECT=false
      - SECURE_SSL_REDIRECT=false
    restart: unless-stopped
    networks:
      - coreldove-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.saleor-backend.rule=Host(`saleor.bizosaas.local`)"

# ===========================================
# NETWORKS
# ===========================================
networks:
  coreldove-network:
    driver: bridge
    name: coreldove-network

# ===========================================
# VOLUMES
# ===========================================
volumes:
  coreldove_data:
    name: coreldove-data