version: '3.8'

# Bizoholic Marketing Stack - Marketing Frontend and Services
# Dokploy Project: bizoholic
# Services: Marketing Website, Content Management

services:
  # ===========================================
  # BIZOHOLIC MARKETING FRONTEND - PORT 3001
  # ===========================================
  
  bizoholic-marketing:
    image: bizoholic-bizoholic-frontend:latest
    container_name: bizoholic-marketing-3001
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BRAIN_API_URL=http://host.docker.internal:8001
      - NEXT_PUBLIC_AUTH_API_URL=http://host.docker.internal:8007
      - NEXT_PUBLIC_WAGTAIL_URL=http://host.docker.internal:8006
      - NEXT_PUBLIC_PLATFORM=bizoholic-marketing
      - WAGTAIL_API_BASE_URL=http://host.docker.internal:8006/api
      - PORT=3000
    restart: unless-stopped
    networks:
      - bizoholic-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bizoholic-marketing.rule=Host(`bizoholic.bizosaas.local`) || Host(`localhost:3001`)"
      - "traefik.http.services.bizoholic-marketing.loadbalancer.server.port=3000"

# ===========================================
# NETWORKS
# ===========================================
networks:
  bizoholic-network:
    driver: bridge
    name: bizoholic-network

# ===========================================
# VOLUMES
# ===========================================
volumes:
  bizoholic_data:
    name: bizoholic-data