
networks:
  bizosaas-platform-network:
    external: true

services:
  # BizOSaaS Admin Dashboard - Port 3009
  bizosaas-admin-dashboard:
    build:
      context: ./frontend/apps/bizosaas-admin
      dockerfile: Dockerfile
    container_name: bizosaas-admin-dashboard-3009
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=production
      - PORT=3009
      - NEXT_PUBLIC_BRAIN_API_URL=http://localhost:8001
      - NEXT_PUBLIC_AUTH_API_URL=http://localhost:8007
      - NEXT_PUBLIC_SUPERSET_URL=http://localhost:8088
      - NEXT_PUBLIC_CRM_API_URL=http://localhost:8008
      - NEXT_PUBLIC_PLATFORM=bizosaas-admin
      - NEXT_PUBLIC_APP_NAME=BizOSaaS Admin Dashboard
      - NEXT_PUBLIC_APP_VERSION=1.0.0
    volumes:
      # Development mode volumes (comment out for production)
      - ./frontend/apps/bizosaas-admin:/app
      - /app/node_modules
      - ./frontend/shared:/app/shared
    networks:
      - bizosaas-platform-network
    depends_on:
      - brain-gateway
      - auth-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3009/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bizosaas-admin.rule=Host(`admin.localhost`) || PathPrefix(`/admin`)"
      - "traefik.http.services.bizosaas-admin.loadbalancer.server.port=3009"

  # Enhanced Client Portal with Chat - Port 3000 (fix sidebar issues)
  bizosaas-client-portal-enhanced:
    image: bizosaas-client-portal:latest
    container_name: bizosaas-client-portal-enhanced-3000
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_BRAIN_API_URL=http://localhost:8001
      - NEXT_PUBLIC_AUTH_API_URL=http://localhost:8007
      - NEXT_PUBLIC_AI_CHAT_URL=http://localhost:8010
      - NEXT_PUBLIC_PLATFORM=client-portal
      - SIDEBAR_PERSISTENT=true
      - CHAT_ENABLED=true
    networks:
      - bizosaas-platform-network
    depends_on:
      - brain-gateway
      - auth-service
      - bizosaas-ai-agents-8010
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # AI Chat Service for both portals
  ai-chat-service:
    image: bizosaas/ai-agents:latest
    container_name: bizosaas-ai-chat-interface-8011
    ports:
      - "8011:8000"
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://postgres:Bizoholic2024Alagiri@bizosaas-postgres-unified:5432/bizosaas
      - REDIS_URL=redis://bizosaas-redis-unified:6379/3
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHAT_MODE=enabled
      - PORTAL_INTEGRATION=true
    networks:
      - bizosaas-platform-network
    depends_on:
      - brain-gateway
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3