version: '3.8'

services:
  # Infrastructure
  postgres:
    image: ankane/pgvector:v0.5.1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: bizosaas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bizosaas-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bizosaas-network

  # Core Backend Services
  ai-governance-layer:
    build:
      context: ./core/services/ai-governance-layer
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      DATABASE_URL: postgresql://admin:securepassword@postgres:5432/bizosaas
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    networks:
      - bizosaas-network

  event-bus:
    build:
      context: ./core/services/event-bus
      dockerfile: Dockerfile
    ports:
      - "8009:8009"
    environment:
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - redis
    networks:
      - bizosaas-network

  wagtail-cms:
    build:
      context: ./core/services/wagtail-cms
      dockerfile: Dockerfile
    ports:
      - "8006:8006"
    environment:
      DATABASE_URL: postgresql://admin:securepassword@postgres:5432/wagtail
      REDIS_URL: redis://redis:6379/2
      SECRET_KEY: wagtail-secret-key-for-development
      DEBUG: "true"
      ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0,wagtail-cms
    depends_on:
      - postgres
      - redis
    networks:
      - bizosaas-network

  api-gateway:
    build:
      context: ./core/services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis://redis:6379/3
    depends_on:
      - redis
    networks:
      - bizosaas-network

  # CRM Services
  django-crm:
    build:
      context: ./crm/services/django-crm
      dockerfile: Dockerfile
    ports:
      - "8007:8007"
    environment:
      DATABASE_URL: postgresql://admin:securepassword@postgres:5432/bizosaas
      REDIS_URL: redis://redis:6379/4
      SECRET_KEY: django-secret-key-for-development
      DEBUG: "true"
    depends_on:
      - postgres
      - redis
    networks:
      - bizosaas-network

  business-directory:
    build:
      context: ./crm/services/business-directory
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    environment:
      DATABASE_URL: postgresql://admin:securepassword@postgres:5432/bizosaas
      REDIS_URL: redis://redis:6379/5
    depends_on:
      - postgres
      - redis
    networks:
      - bizosaas-network

  # AI Services
  bizosaas-brain:
    build:
      context: ./ai/services/bizosaas-brain
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://admin:securepassword@postgres:5432/bizosaas
      REDIS_URL: redis://redis:6379/6
      OPENAI_API_KEY: ${OPENAI_API_KEY:-dummy-key}
    depends_on:
      - postgres
      - redis
    networks:
      - bizosaas-network

  # E-commerce Services
  saleor-backend:
    image: ghcr.io/saleor/saleor:latest
    ports:
      - "8020:8000"
    environment:
      DATABASE_URL: postgresql://admin:securepassword@postgres:5432/saleor
      REDIS_URL: redis://redis:6379/7
      SECRET_KEY: saleor-secret-key-for-development
      DEBUG: "true"
      ALLOWED_HOSTS: localhost,127.0.0.1,saleor-backend
    depends_on:
      - postgres
      - redis
    networks:
      - bizosaas-network

  saleor-dashboard:
    image: ghcr.io/saleor/saleor-dashboard:latest
    ports:
      - "9020:80"
    environment:
      API_URI: http://localhost:8020/graphql/
    depends_on:
      - saleor-backend
    networks:
      - bizosaas-network

  # Frontend Services
  bizoholic-frontend:
    build:
      context: ./frontend/apps/bizoholic-frontend
      dockerfile: ../../../misc/services/bizoholic-frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8001
      NEXT_PUBLIC_CMS_URL: http://localhost:8006
      NEXT_PUBLIC_CRM_URL: http://localhost:8007
    depends_on:
      - bizosaas-brain
      - wagtail-cms
      - django-crm
    networks:
      - bizosaas-network

  coreldove-frontend:
    build:
      context: ./ecommerce/services/coreldove-frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_SALEOR_API_URL: http://localhost:8020/graphql/
      NEXT_PUBLIC_API_URL: http://localhost:8001
    depends_on:
      - saleor-backend
      - bizosaas-brain
    networks:
      - bizosaas-network

  bizosaas-admin:
    build:
      context: ./frontend/apps/bizosaas-admin
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8001
      NEXT_PUBLIC_GOVERNANCE_URL: http://localhost:8090
      NEXT_PUBLIC_CRM_URL: http://localhost:8007
    depends_on:
      - bizosaas-brain
      - ai-governance-layer
      - django-crm
    networks:
      - bizosaas-network

volumes:
  postgres_data:
  redis_data:

networks:
  bizosaas-network:
    driver: bridge