# BizoSaaS Complete AI Agent Hierarchy
# Comprehensive multi-level agent organization for end-to-end digital marketing automation

apiVersion: crewai/v1
kind: AgentHierarchy
metadata:
  name: bizosaas-agent-hierarchy
  version: "1.0.0"
  description: "Complete hierarchical AI agent structure for autonomous digital marketing agency"

# ============================================================================
# TOP LEVEL - EXECUTIVE ORCHESTRATION
# ============================================================================

executive_layer:
  ceo_agent:
    name: "CEO_Orchestrator"
    service: "bizosaas-agent-orchestration" # Existing service (port 30320)
    role: "Chief Executive Orchestrator"
    responsibilities:
      - "Global strategy coordination"
      - "Resource allocation across all clients"
      - "Quality assurance and oversight"
      - "Performance optimization decisions"
      - "Escalation handling"
    tools:
      - "system_monitor"
      - "resource_allocator"
      - "quality_assessor"
      - "escalation_handler"
    reports_to: "Human Supervisor (HITL enabled)"

# ============================================================================
# DIRECTOR LEVEL - FUNCTIONAL LEADERS
# ============================================================================

director_layer:
  strategy_director:
    name: "Strategy_Director"
    service: "bizosaas-strategy-agent" # New service (port 30311)
    role: "Strategic Planning Director"
    responsibilities:
      - "Market research coordination"
      - "Competitive analysis oversight"
      - "Budget optimization strategies"
      - "Multi-channel strategy development"
      - "ROI forecasting"
    subordinates:
      - "market_research_agent"
      - "competitor_analysis_agent"
      - "budget_optimization_agent"
      - "channel_strategy_agent"
    reports_to: "ceo_agent"

  operations_director:
    name: "Operations_Director"
    service: "bizosaas-operations-agent" # New service (port 30314)
    role: "Operations & Delivery Director"
    responsibilities:
      - "Client onboarding oversight"
      - "Campaign execution management"
      - "Setup process coordination"
      - "Quality control"
    subordinates:
      - "onboarding_manager"
      - "campaign_manager"
      - "setup_manager"
    reports_to: "ceo_agent"

  analytics_director:
    name: "Analytics_Director"
    service: "bizosaas-analytics-ai" # Existing service (port 30308)
    role: "Analytics & Performance Director"
    responsibilities:
      - "Performance monitoring coordination"
      - "ROI calculation and reporting"
      - "Data analysis and insights"
      - "Predictive analytics"
    subordinates:
      - "performance_monitor_agent"
      - "roi_calculator_agent"
      - "report_generator_agent"
      - "predictive_analytics_agent"
    reports_to: "ceo_agent"

  compliance_director:
    name: "Compliance_Director"
    service: "bizosaas-compliance-agent" # New service (port 30315)
    role: "Compliance & Security Director"
    responsibilities:
      - "GDPR compliance monitoring"
      - "Data security oversight"
      - "Audit trail management"
      - "Risk assessment"
    subordinates:
      - "gdpr_monitor_agent"
      - "security_audit_agent"
      - "data_isolation_agent"
    reports_to: "ceo_agent"

# ============================================================================
# MANAGER LEVEL - SPECIALIZED COORDINATORS
# ============================================================================

manager_layer:
  onboarding_manager:
    name: "Onboarding_Manager"
    service: "bizosaas-onboarding-agent" # New service (port 30310)
    role: "Client Onboarding Manager"
    responsibilities:
      - "Guided onboarding process"
      - "Client profile building"
      - "Initial audit coordination"
      - "Information collection"
    subordinates:
      - "profile_builder_agent"
      - "audit_coordinator_agent"
      - "information_collector_agent"
    reports_to: "operations_director"

  campaign_manager:
    name: "Campaign_Manager"
    service: "bizosaas-campaign-agent" # New service (port 30316)
    role: "Multi-Channel Campaign Manager"
    responsibilities:
      - "Campaign strategy execution"
      - "Channel coordination"
      - "Performance optimization"
      - "A/B testing management"
    subordinates:
      - "google_ads_agent"
      - "meta_ads_agent"
      - "linkedin_agent"
      - "amazon_agent"
      - "appstore_agent"
      - "youtube_agent"
      - "tiktok_agent"
      - "email_marketing_agent"
      - "sms_marketing_agent"
    reports_to: "operations_director"

  setup_manager:
    name: "Setup_Manager"
    service: "bizosaas-setup-agent" # New service (port 30312)
    role: "Campaign Setup & Integration Manager"
    responsibilities:
      - "Campaign setup automation"
      - "Credential management"
      - "Platform integrations"
      - "Technical configuration"
    subordinates:
      - "credential_handler_agent"
      - "integration_agent"
      - "configuration_agent"
    reports_to: "operations_director"

# ============================================================================
# SPECIALIST LEVEL - EXECUTION AGENTS
# ============================================================================

specialist_layer:
  # Market Intelligence Specialists
  market_research_agent:
    name: "Market_Research_Specialist"
    service: "bizosaas-marketing-ai" # Existing service (port 30307)
    role: "Market Intelligence Specialist"
    tools:
      - "serp_analyzer"
      - "trend_analyzer"
      - "keyword_research"
      - "market_size_calculator"
    capabilities:
      - "Industry analysis"
      - "Market trend identification"
      - "Competitive landscape mapping"
      - "Target audience research"

  competitor_analysis_agent:
    name: "Competitor_Analysis_Specialist"
    service: "bizosaas-marketing-ai"
    role: "Competitive Intelligence Specialist"
    tools:
      - "competitor_tracker"
      - "pricing_analyzer"
      - "feature_comparator"
      - "ad_spy_tools"
    capabilities:
      - "Competitor ad analysis"
      - "Pricing strategy analysis"
      - "Feature gap identification"
      - "Market positioning insights"

  # Channel Specialists
  google_ads_agent:
    name: "Google_Ads_Specialist"
    service: "bizosaas-campaign-agent"
    role: "Google Ads Campaign Specialist"
    tools:
      - "google_ads_api"
      - "keyword_planner"
      - "google_analytics"
      - "google_tag_manager"
    capabilities:
      - "Search campaign creation"
      - "Display campaign management"
      - "YouTube ads optimization"
      - "Shopping campaign setup"
      - "Performance max campaigns"

  meta_ads_agent:
    name: "Meta_Ads_Specialist"
    service: "bizosaas-campaign-agent"
    role: "Facebook/Instagram Ads Specialist"
    tools:
      - "facebook_ads_api"
      - "instagram_business_api"
      - "facebook_pixel"
      - "audience_insights"
    capabilities:
      - "Facebook ads creation"
      - "Instagram story ads"
      - "Audience targeting optimization"
      - "Creative testing automation"

  amazon_agent:
    name: "Amazon_Specialist"
    service: "bizosaas-campaign-agent"
    role: "Amazon Platform Optimization Specialist"
    tools:
      - "amazon_advertising_api"
      - "amazon_seller_central"
      - "sponsored_products_api"
      - "brand_registry_tools"
    capabilities:
      - "Product listing optimization"
      - "Amazon PPC campaigns"
      - "Brand store setup"
      - "Inventory management"

  appstore_agent:
    name: "AppStore_Specialist"
    service: "bizosaas-campaign-agent"
    role: "App Store Optimization Specialist"
    tools:
      - "app_store_connect_api"
      - "google_play_developer_api"
      - "aso_optimization_tools"
      - "app_analytics"
    capabilities:
      - "App store listing optimization"
      - "Keyword optimization for apps"
      - "Review management"
      - "App store ads campaigns"

  # Content & Creative Specialists
  content_generation_agent:
    name: "Content_Generation_Specialist"
    service: "bizosaas-marketing-ai"
    role: "AI Content Creation Specialist"
    tools:
      - "openai_api"
      - "claude_api"
      - "image_generation_api"
      - "video_generation_tools"
    capabilities:
      - "Ad copy generation"
      - "Blog content creation"
      - "Social media content"
      - "Email templates"
      - "Landing page copy"

  # Technical Specialists
  credential_handler_agent:
    name: "Credential_Handler"
    service: "bizosaas-setup-agent"
    role: "Secure Credential Management Specialist"
    tools:
      - "hashicorp_vault"
      - "encryption_tools"
      - "oauth_manager"
      - "api_key_rotator"
    capabilities:
      - "Secure credential storage"
      - "API key management"
      - "OAuth token handling"
      - "Access control management"

  integration_agent:
    name: "Integration_Specialist"
    service: "bizosaas-setup-agent"
    role: "Platform Integration Specialist"
    tools:
      - "api_connectors"
      - "webhook_manager"
      - "data_sync_tools"
      - "integration_monitor"
    capabilities:
      - "Third-party API integration"
      - "Data synchronization"
      - "Webhook configuration"
      - "Integration testing"

  # Monitoring & Compliance Specialists
  performance_monitor_agent:
    name: "Performance_Monitor"
    service: "bizosaas-monitoring-agent" # New service (port 30313)
    role: "Real-time Performance Monitor"
    tools:
      - "real_time_tracker"
      - "alert_system"
      - "performance_analyzer"
      - "anomaly_detector"
    capabilities:
      - "24/7 campaign monitoring"
      - "Performance anomaly detection"
      - "Real-time alerts"
      - "Optimization recommendations"

  gdpr_monitor_agent:
    name: "GDPR_Monitor"
    service: "bizosaas-compliance-agent"
    role: "GDPR Compliance Monitor"
    tools:
      - "consent_manager"
      - "data_audit_tools"
      - "privacy_scanner"
      - "compliance_checker"
    capabilities:
      - "Consent management"
      - "Data processing audits"
      - "Privacy compliance checking"
      - "Data retention management"

# ============================================================================
# COMMUNICATION & COLLABORATION PROTOCOLS
# ============================================================================

communication_protocols:
  hierarchical_communication:
    - "Agents report to immediate supervisor only"
    - "Cross-department communication via directors"
    - "Emergency escalation to CEO_Orchestrator"
    - "Weekly performance reports to human supervisor"

  task_delegation:
    - "Tasks flow down the hierarchy"
    - "Results flow up the hierarchy"
    - "Peers can share information directly"
    - "Cross-functional collaboration allowed"

  decision_making:
    - "Operational decisions at manager level"
    - "Strategic decisions at director level"
    - "Critical decisions at CEO level"
    - "Human override available at all levels"

# ============================================================================
# HUMAN-IN-THE-LOOP CONTROLS
# ============================================================================

hitl_controls:
  approval_thresholds:
    budget_approvals:
      - "< $500: Automatic"
      - "$500-$5000: Manager approval"
      - "$5000-$50000: Director approval"
      - "> $50000: Human approval required"
    
    campaign_launches:
      - "A/B tests: Automatic"
      - "New campaigns: Manager approval"
      - "Strategic changes: Director approval"
      - "Major pivots: Human approval required"

  override_capabilities:
    super_admin:
      - "Global system override"
      - "All agent control"
      - "Emergency stop functionality"
      - "System configuration changes"
    
    agency_manager:
      - "Client-specific overrides"
      - "Campaign modifications"
      - "Budget adjustments"
      - "Team management"

  monitoring_levels:
    real_time: "Performance monitoring, alerts"
    daily: "Campaign performance reports"
    weekly: "Strategic performance reviews"
    monthly: "Comprehensive audits and optimizations"

# ============================================================================
# LEARNING & OPTIMIZATION SYSTEMS
# ============================================================================

learning_systems:
  rag_implementation:
    knowledge_base:
      - "Client historical data"
      - "Campaign performance history"
      - "Industry best practices"
      - "Competitive intelligence"
    
    retrieval_system:
      - "Context-aware information retrieval"
      - "Similar campaign identification"
      - "Best practice recommendations"
      - "Historical pattern analysis"

  kag_implementation:
    knowledge_graph:
      - "Client relationship mapping"
      - "Campaign dependency tracking"
      - "Channel interaction modeling"
      - "Attribution path mapping"
    
    reasoning_system:
      - "Causal relationship inference"
      - "Multi-channel attribution"
      - "Customer journey mapping"
      - "Optimization opportunity identification"

  feedback_loops:
    performance_feedback:
      - "Real-time campaign adjustments"
      - "A/B test result integration"
      - "Budget reallocation automation"
      - "Creative optimization cycles"
    
    learning_integration:
      - "Model fine-tuning based on results"
      - "Strategy refinement over time"
      - "Personalization improvements"
      - "Predictive model updates"

# ============================================================================
# SERVICE DEPLOYMENT CONFIGURATION
# ============================================================================

service_mappings:
  existing_services:
    - name: "bizosaas-agent-orchestration"
      port: 30320
      agents: ["ceo_agent"]
    - name: "bizosaas-marketing-ai"
      port: 30307
      agents: ["market_research_agent", "competitor_analysis_agent", "content_generation_agent"]
    - name: "bizosaas-analytics-ai"
      port: 30308
      agents: ["analytics_director", "report_generator_agent"]

  new_services_required:
    - name: "bizosaas-strategy-agent"
      port: 30311
      agents: ["strategy_director", "budget_optimization_agent", "channel_strategy_agent"]
    - name: "bizosaas-onboarding-agent"
      port: 30310
      agents: ["onboarding_manager", "profile_builder_agent", "audit_coordinator_agent"]
    - name: "bizosaas-setup-agent"
      port: 30312
      agents: ["setup_manager", "credential_handler_agent", "integration_agent"]
    - name: "bizosaas-monitoring-agent"
      port: 30313
      agents: ["performance_monitor_agent", "anomaly_detector"]
    - name: "bizosaas-operations-agent"
      port: 30314
      agents: ["operations_director"]
    - name: "bizosaas-compliance-agent"
      port: 30315
      agents: ["compliance_director", "gdpr_monitor_agent", "security_audit_agent"]
    - name: "bizosaas-campaign-agent"
      port: 30316
      agents: ["campaign_manager", "google_ads_agent", "meta_ads_agent", "amazon_agent", "appstore_agent"]

# ============================================================================
# INTEGRATION REQUIREMENTS
# ============================================================================

external_integrations:
  advertising_platforms:
    - "Google Ads API"
    - "Facebook/Meta Business API"
    - "LinkedIn Marketing API"
    - "Amazon Advertising API"
    - "TikTok Business API"
    - "YouTube Data API"
    - "Pinterest Business API"
    - "Snapchat Ads API"
    - "Twitter Ads API"

  tools_and_services:
    - "HashiCorp Vault (credential management)"
    - "Strapi CMS (content management)"
    - "PostgreSQL (data storage)"
    - "Dragonfly Cache (performance)"
    - "n8n (workflow automation)"
    - "Traefik (ingress routing)"

  analytics_platforms:
    - "Google Analytics"
    - "Facebook Analytics"
    - "Adobe Analytics"
    - "Mixpanel"
    - "Amplitude"
    - "Hotjar"

security_requirements:
  data_isolation:
    - "Multi-tenant data separation"
    - "Client-specific credential isolation"
    - "Campaign data segregation"
    - "Audit trail separation"

  compliance_measures:
    - "GDPR compliance automation"
    - "Data retention policies"
    - "Consent management"
    - "Right to erasure automation"
    - "Data portability features"

  access_controls:
    - "Role-based access control (RBAC)"
    - "API key rotation"
    - "Multi-factor authentication"
    - "Session management"
    - "Audit logging"