# BMAD Core Configuration
# Business Methodology for Agile Development
# Shared configuration for all projects

bmad_version: "1.0.0"
created: "2025-08-22"
projects_supported: 6

# Core BMAD Principles
methodology:
  business_first: true
  agile_development: true
  agent_driven: true
  context_aware: true

# Agent Flow Configuration
agent_flow:
  sequence: ["analyst", "architect", "dev", "qa", "pm"]
  iteration_cycle: true
  feedback_loops: true

# PRD Management
prd_config:
  prdSharded: true
  sharding_strategy: "epic_based"
  max_shard_size: 5000  # tokens
  context_overlap: 500   # tokens

# Story Management
story_config:
  devStoryLocation: "docs/stories/"
  story_format: "markdown"
  linking_enabled: true
  git_sync: true

# Context Management
context_config:
  devLoadAlwaysFiles:
    - "CLAUDE.md"
    - "README.md" 
    - "package.json"
    - "docs/prd.md"
    - "docs/architecture.md"
  context_inheritance: true
  context_caching: true

# Quality Standards
quality_standards:
  code_review: "mandatory"
  testing: "comprehensive"
  documentation: "always_updated"
  security_scan: "automated"

# Integration Points
integrations:
  git:
    enabled: true
    branch_strategy: "feature_branch"
    commit_format: "[BMAD:{agent}] {description}"
  
  mobile:
    enabled: true
    approval_required: true
    notification_enabled: true
  
  shared_deployment:
    enabled: true
    deployment_engine: "shared-deployment/core/deploy-engine.sh"

# Project Templates
templates:
  wordpress:
    type: "content_management"
    agents: ["analyst", "architect", "dev", "qa", "pm"]
    specialized_tools: ["wordpress_sync", "content_audit"]
    
  ai_assistant:
    type: "ai_platform"
    agents: ["analyst", "architect", "dev", "qa", "pm"]
    specialized_tools: ["ai_model_testing", "conversation_flow"]
    
  trading:
    type: "financial_system"
    agents: ["analyst", "architect", "dev", "qa", "pm"]
    specialized_tools: ["risk_analysis", "backtesting"]
    
  infrastructure:
    type: "devops_platform"
    agents: ["analyst", "architect", "dev", "qa", "pm"]
    specialized_tools: ["cluster_management", "deployment_validation"]
    
  generic:
    type: "general_purpose"
    agents: ["analyst", "architect", "dev", "qa", "pm"]
    specialized_tools: []