# BMAD Project Configuration - Bizoholic
# AI Marketing Agency SaaS platform with CrewAI integration

project_name: "bizoholic"
project_type: "ai_platform"
business_model: "marketing_saas"

# Project Specific Configuration
project_config:
  domain: "bizoholic.com"
  primary_technology: "crewai"
  secondary_technology: "n8n"
  database: "postgresql_pgvector"
  deployment_target: "vps"

# Business Context
business_context:
  target_market: "small_medium_businesses"
  key_objectives:
    - "ai_marketing_automation"
    - "client_campaign_optimization"
    - "automated_reporting"
    - "multi_platform_integration"
  
  success_metrics:
    - "client_roi_improvement"
    - "campaign_performance"
    - "automation_efficiency"
    - "client_retention"

# Agent Specialization
agent_specialization:
  analyst:
    focus: ["market_analysis", "client_requirements", "campaign_strategy"]
    tools: ["crewai_agents", "analytics_apis", "market_research"]
    
  architect:
    focus: ["ai_agent_design", "campaign_architecture", "integration_planning"]
    tools: ["crewai_framework", "api_design", "workflow_architecture"]
    
  dev:
    focus: ["crewai_implementation", "n8n_workflows", "ai_model_integration"]
    tools: ["python_fastapi", "crewai_tools", "langchain"]
    
  qa:
    focus: ["ai_output_validation", "campaign_testing", "performance_monitoring"]
    tools: ["ai_testing_frameworks", "campaign_simulators", "metrics_validation"]
    
  pm:
    focus: ["client_delivery", "campaign_coordination", "performance_reporting"]
    tools: ["client_dashboards", "reporting_automation", "project_coordination"]

# Development Priorities
development_priorities:
  1: "ai_agent_optimization"
  2: "client_onboarding_automation"
  3: "campaign_performance_analytics"
  4: "multi_platform_integration"
  5: "client_portal_enhancement"

# AI Integration
ai_integration:
  crewai_agents:
    - "digital_presence_audit"
    - "campaign_strategy"
    - "content_generation"
    - "performance_optimization"
  
  language_models:
    - "openai_gpt4"
    - "anthropic_claude"
    - "custom_fine_tuned"

# Integration Points
integrations:
  marketing_platforms:
    - "google_ads"
    - "meta_ads"
    - "linkedin_marketing"
    - "email_platforms"
  
  analytics_tools:
    - "google_analytics"
    - "facebook_analytics"
    - "custom_dashboards"

# Quality Gates
quality_gates:
  ai_accuracy: "> 85%"
  client_satisfaction: "> 90%"
  campaign_performance: "> baseline + 20%"
  system_uptime: "> 99.5%"