version: '3.8'

services:
  # QuantTrade Frontend - Next.js Trading Interface (Port 3012)
  quanttrade-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quanttrade-frontend-3012
    ports:
      - "3012:3012"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://quanttrade-backend:8012
      - NEXT_PUBLIC_WS_URL=ws://quanttrade-backend:8012
      - QUANTTRADE_API_URL=http://quanttrade-backend:8012
      - TRADINGVIEW_WIDGET_ID=quanttrade-charts
      - PORT=3012
      - HOSTNAME=0.0.0.0
    networks:
      - bizosaas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3012/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quanttrade-frontend.rule=Host(`quanttrade.localhost`)"
      - "traefik.http.routers.quanttrade-frontend.entrypoints=web"
      - "traefik.http.services.quanttrade-frontend.loadbalancer.server.port=3012"
    depends_on:
      - quanttrade-backend
    volumes:
      # Mount for hot reload in development (comment out in production)
      # - ./frontend:/app:cached
      # - /app/node_modules
      # - /app/.next

      # Logs volume for debugging
      - quanttrade-frontend-logs:/app/logs

  # QuantTrade Backend - FastAPI + VectorBT + CrewAI Trading Agents (Port 8012)
  quanttrade-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quanttrade-backend-8012
    ports:
      - "8012:8012"
    environment:
      # Application
      - ENVIRONMENT=production
      - DEBUG=false
      - SECRET_KEY=quanttrade-production-secret-key-change-me
      - ALLOWED_HOSTS=["*"]

      # Database
      - DATABASE_URL=postgresql+asyncpg://quanttrade:quanttrade@postgres:5432/quanttrade
      - REDIS_URL=redis://redis:6379/0

      # Market Data APIs (add your API keys)
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY:-}
      - POLYGON_API_KEY=${POLYGON_API_KEY:-}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY:-}

      # AI Services
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}

      # Trading Configuration
      - DEFAULT_PORTFOLIO_VALUE=100000.0
      - ENABLE_PAPER_TRADING=true
      - ENABLE_REAL_TRADING=false

      # Python Environment
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - bizosaas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8012/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quanttrade-backend.rule=Host(`quanttrade-api.localhost`)"
      - "traefik.http.routers.quanttrade-backend.entrypoints=web"
      - "traefik.http.services.quanttrade-backend.loadbalancer.server.port=8012"
    volumes:
      # Data persistence
      - quanttrade-backend-data:/app/data
      - quanttrade-backend-logs:/app/logs

      # Development volume mounts (uncomment for development)
      # - ./backend/app:/app/app:cached

volumes:
  quanttrade-frontend-logs:
    name: quanttrade-frontend-logs
  quanttrade-backend-data:
    name: quanttrade-backend-data
  quanttrade-backend-logs:
    name: quanttrade-backend-logs

networks:
  bizosaas-network:
    name: bizosaas-network
    external: true