version: '3.8'

services:
  temporal-integration:
    build: .
    container_name: bizosaas-temporal-integration
    ports:
      - "8202:8202"
    environment:
      - TEMPORAL_URL=bizosaas-temporal:7233
      - TEMPORAL_NAMESPACE=bizosaas
      - AI_AGENTS_URL=http://bizosaas-ai-agents:8000
      - VAULT_URL=http://bizosaas-vault:8200
      - VAULT_TOKEN=bizosaas-root-token
    depends_on:
      - temporal
      - temporal-ui
    networks:
      - bizosaas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8202/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  temporal:
    image: temporalio/auto-setup:1.20.0
    container_name: bizosaas-temporal
    ports:
      - "7233:7233"
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PWD=BizoholicSecure2025
      - POSTGRES_SEEDS=bizosaas-postgres
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    volumes:
      - ./temporal-config:/etc/temporal/config/dynamicconfig
    depends_on:
      - postgres
    networks:
      - bizosaas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "tctl", "--address", "localhost:7233", "namespace", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  temporal-ui:
    image: temporalio/ui:2.10.0
    container_name: bizosaas-temporal-ui
    ports:
      - "8088:8088"
    environment:
      - TEMPORAL_ADDRESS=bizosaas-temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000,http://localhost:8088
    depends_on:
      - temporal
    networks:
      - bizosaas-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: bizosaas-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bizosaas
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=BizoholicSecure2025
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - bizosaas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d bizosaas"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  bizosaas-network:
    external: true

volumes:
  postgres-data:
  temporal-data: